'use strict';
const SkillRules=CafeChallenge;
progress.disabledDecor=Array.isArray(progress.disabledDecor)?progress.disabledDecor:[];
progress.reviews=Array.isArray(progress.reviews)?progress.reviews.slice(-20):[];
let mini=null,miniFrame=0,shopTab='all',shopPreview=null,lastClock=performance.now();
const decorIds=['plant','lights','lavender','flowers','pet-beds'];
const groupFor=u=>['pet-beds','treats'].includes(u.id)?'pets':decorIds.includes(u.id)?'decor':'tools';
function mood(){if(state.serving)return state.lastRating>=4?'happy':state.lastRating===3?'neutral':'upset';const c=state.customerClock;if(!c)return 'calm';const ratio=c.left/c.total;return ratio>.65?'calm':ratio>.35?'watching':ratio>.15?'impatient':'upset'}
const moodLines={calm:'Te mira con curiosidad. Hay tiempo para hacerlo bien.',watching:'Sigue cada movimiento de tus manos…',impatient:'Mira el reloj y tamborilea en el mostrador.',upset:'Frunce el ceño. La espera se está haciendo larga.',happy:'Se ilumina su cara y se despide con una sonrisa.',neutral:'Asiente, aunque esperaba un poquito más.'};
const moodIcons={calm:'♡',watching:'…',impatient:'⌛',upset:'!',happy:'♥',neutral:'…'};
function clockPaused(){const m=$('.modal');return document.hidden||!!(m&&!m.classList.contains('challenge-modal')&&!m.classList.contains('menu-modal'))}
function patienceHtml(){const c=state.customerClock;if(!c)return '';return `<div class="patience-head"><span>${clockPaused()?'Pausa · leyendo o mirando la tienda':'Paciencia del cliente'}</span><b class="patience-seconds">${Math.ceil(c.left)} s</b></div><div class="patience-track"><i style="width:${100*c.left/c.total}%"></i></div>`}
function watchHtml(){const o=state.orders[0],m=mood();return `<div class="watch-portrait">${sprite(o.sprite,'',o.name)}<span class="emotion-mark">${moodIcons[m]}</span></div><div><strong>${esc(o.name)} te está mirando</strong><p class="live-mood-line">${moodLines[m]}</p><div class="live-patience">${patienceHtml()}</div></div>`}
function initCustomer(){const o=state.orders[0];const total=SkillRules.budget(progress.day,o.number,o.items.length,hasUpgrade('flowers'));state.customerClock={total,left:total,mistakes:0,soothed:false};state.customerPhase='entering';later(()=>{if(state.scene==='work'&&!state.serving){state.customerPhase='waiting';render()}},1400)}
const challengeWork=work;
work=function(){const m=mood();let html=challengeWork();html=html.replace('<div class="customer-stage">',`<div class="customer-stage mood-stage" data-mood="${m}">`);html=html.replace(/<div class="customer-message">[\s\S]*?<\/div><div class="counter-edge">/,`<div class="customer-message"><span class="eyebrow">${state.serving?'ASÍ SE VA DEL CAFÉ':'TE ESTÁ MIRANDO'}</span><h3>${state.orders[0].name} <span class="emotion-mark-inline">${moodIcons[m]}</span></h3><p class="live-mood-line">${state.serving?esc(state.lastFeedback):moodLines[m]}</p>${state.serving?`<strong>${'★'.repeat(state.lastRating)}${'☆'.repeat(5-state.lastRating)} · +${state.lastEarning} ✦</strong>`:''}</div><div class="counter-edge">`);
 html=html.replace('<article class="ticket">',`<div class="customer-pressure"><div class="live-patience">${patienceHtml()}</div>${hasUpgrade('bell')?button(state.customerClock?.soothed?'Ya lo tranquilizaste':'♧ Avisarle que ya sale · +12 s','soothe','text-button',state.customerClock?.soothed||state.serving?'disabled':''):''}</div><article class="ticket">`);
 html=html.replace('No hay reloj. Revisá el ticket y disfrutá preparando cada cosa.','La calidad, la espera y los errores cambian la propina. Abrir la tienda o el recetario pausa el reloj.');
 html=html.replace('Cinco pedidos, cinco pequeñas alegrías.','Cada cliente tiene su propia opinión.');
 html=html.replace('Un pedido, una sonrisa.','Manos a la obra.').replace('clientes atendidos','clientes de este turno');
 let qualityIndex=0;html=html.replace(/<\/span><b>×<\/b>/g,()=>`<small class="tray-quality">Calidad: ${Math.round(state.tray[qualityIndex++]?.quality||0)}/100</small></span><b>×</b>`);
 return html;
};
startWork=function(){clearScene();stopMini();closeModal();state={...state,scene:'work',orders:[createOrder(1)],tray:[],completed:0,earned:0,delivery:'here',prep:null,serving:false,shiftReviews:[],streak:0};initCustomer();render();if(!progress.challengeIntro){progress.challengeIntro=true;save();modal(`<span class="eyebrow">COCINA CON LAS MANOS</span><h2>Hoy el desafío es de verdad.</h2><p>Arrastrá ingredientes en orden, trazá, mezclá y controlá el punto. Cada producto conserva la calidad que lograste.</p><p>Los clientes observan y pierden paciencia. Un pedido perfecto y rápido deja más estrellas; uno flojo puede recibir solo una. Si se acaba el tiempo, se van.</p><p><b>El reloj se pausa al abrir ayuda, tienda o recetario y al cambiar de pestaña.</b> Durante la receta sigue corriendo.</p>${button('¡A cocinar!','close')}`)}};
function finishCustomer(delivered){if(state.serving||state.scene!=='work')return;const o=state.orders[0],c=state.customerClock;stopMini();state.prep=null;closeModal();const quality=delivered?state.tray.reduce((s,p)=>s+(Number(p.quality)||0),0)/Math.max(1,state.tray.length):0;const r=delivered?SkillRules.evaluate(quality,c.left,c.total,c.mistakes):{stars:1,score:0,quality:0,pace:0};state.streak=r.stars>=4?(state.streak||0)+1:0;const pay=delivered?SkillRules.earnings(o.items.reduce((s,p)=>s+item(p.id).price,0),r.stars,state.streak-1):{base:0,tip:0};state.lastRating=r.stars;state.lastEarning=pay.base+pay.tip;state.lastFeedback=!delivered?'“Me tengo que ir… vuelvo cuando haya menos espera.”':({5:'“¡Qué delicia! El punto y la presentación están perfectos.”',4:'“¡Muy rico! Se nota el cariño. Gracias.”',3:'“Estuvo bien… aunque podría estar más cuidado.”',2:'“No era lo que esperaba. Le faltó un mejor punto.”',1:'“Hoy no salió bien… espero que la próxima sea mejor.”'}[r.stars]);const review={name:o.name,...r,tip:pay.tip,earned:state.lastEarning,delivered,at:Date.now()};state.shiftReviews.push(review);progress.reviews.push(review);progress.reviews=progress.reviews.slice(-20);state.earned+=state.lastEarning;progress.coins+=state.lastEarning;if(delivered)progress.served++;state.completed++;state.tray=[];state.serving=true;state.customerPhase='reacting';save();render();later(()=>{state.customerPhase='leaving';render()},1600);later(()=>{state.serving=false;if(state.completed>=5){progress.day++;progress.best=Math.max(progress.best,state.earned);save();state.scene='summary';render()}else{state.orders=[createOrder(state.completed+1)];state.delivery='here';initCustomer();render()}},3300)}
serve=function(){if(state.serving||state.scene!=='work')return;const o=state.orders[0],r=validateOrder(o.items,state.tray,o.delivery,state.delivery);if(!r.ok){state.customerClock.mistakes++;state.customerClock.left=Math.max(0,state.customerClock.left-8);toast(r.reason+' El cliente perdió paciencia (−8 s).');updatePressure();return}finishCustomer(true)};
summary=function(){const reviews=state.shiftReviews||[],happy=reviews.filter(r=>r.stars>=4).length;return `<main class="shift-summary"><span class="eyebrow">EL CUADERNO DE OPINIONES · TURNO TERMINADO</span><h1>Cada pedido cuenta.</h1><p>${happy} de ${reviews.length} clientes se fueron contentos. Tus estrellas ganadas: <b>${state.earned} ✦</b>.</p><div class="review-grid">${reviews.map(r=>`<article><h3>${esc(r.name)}</h3><div class="review-stars">${'★'.repeat(r.stars)}${'☆'.repeat(5-r.stars)}</div><p>${r.delivered?'Calidad '+r.quality+'/100 · propina '+r.tip+' ✦':'Se fue por la espera'}</p><strong>+${r.earned} ✦</strong></article>`).join('')}</div><div class="summary-actions">${button('Otro turno →','work')}${button('Mejorar la cafetería ✦','shop','secondary')}${button('Descansar y merendar','guest','secondary')}</div></main>${dialogue('DELFI',happy>=4?'¡Qué buen equipo! Se fueron con ganas de volver.':'Miremos qué salió flojo: el punto, los ingredientes o la espera. En el próximo turno podemos mejorar.',button('Volver a la entrada','home','text-button'))}`};
function updatePressure(){if(state.scene!=='work'||!state.customerClock)return;const m=mood();document.querySelectorAll('.live-patience').forEach(e=>e.innerHTML=patienceHtml());document.querySelectorAll('.mood-stage,.customer-watch').forEach(e=>e.dataset.mood=m);if(!state.serving)document.querySelectorAll('.live-mood-line').forEach(e=>e.textContent=moodLines[m]);document.querySelectorAll('.emotion-mark,.emotion-mark-inline').forEach(e=>e.textContent=moodIcons[m])}
setInterval(()=>{const now=performance.now(),dt=Math.min(1,(now-lastClock)/1000);lastClock=now;if(state.scene!=='work'||state.serving||!state.customerClock)return;if(!clockPaused()&&state.customerPhase!=='entering')state.customerClock.left=Math.max(0,state.customerClock.left-dt);updatePressure();if(state.customerClock.left<=0)finishCustomer(false)},250);
const challengeOrnaments=ornaments;
ornaments=function(){return challengeOrnaments()+(hasUpgrade('flowers')?'<div class="welcome-flowers" title="Flores de bienvenida: +15 segundos de paciencia">❁ ❀ ❁</div>':'')};
function shopIcon(id){const drawings={
plant:'<path d="M32 45V17m0 17C12 34 10 13 13 12c20 0 19 22 19 22Zm0-8C32 9 49 5 53 8c0 18-21 18-21 18Z"/><path d="M18 43h28l-5 17H23Z" fill="#c58c64"/>',
lights:'<path d="M5 10q27 20 54 0"/><path d="M15 16v9m17-4v9m17-13v9"/><circle cx="15" cy="30" r="6" fill="#e4bd69"/><circle cx="32" cy="35" r="6" fill="#e4bd69"/><circle cx="49" cy="31" r="6" fill="#e4bd69"/>',
lavender:'<path d="M7 27h50v22H7Z" fill="#c6afd1"/><path d="M14 49v11m36-11v11M32 27V8"/><circle cx="32" cy="12" r="5" fill="#ba98cd"/>',
'pet-beds':'<path d="M7 32q25-22 50 0v20H7Z" fill="#c6afd1"/><ellipse cx="32" cy="44" rx="25" ry="10" fill="#eadfed"/>',
treats:'<rect x="16" y="16" width="32" height="42" rx="8" fill="#e7c898"/><path d="M13 15h38V7H13Z"/><circle cx="26" cy="33" r="4"/><circle cx="39" cy="43" r="4"/>',
oven:'<rect x="9" y="8" width="46" height="51" rx="5" fill="#ddd2be"/><path d="M17 24h30v27H17Z" fill="#c89c69"/><circle cx="20" cy="16" r="2"/><circle cx="44" cy="16" r="2"/><path d="M24 46q-7-7 0-15m10 15q-7-7 0-15"/>',
grinder:'<path d="M13 9h32v45H18Zm32 8q22 0 8 23H45" fill="#e5d7bb"/><path d="M20 25h14m-14 9h9m-9 9h14"/>',
whisk:'<path d="M29 6h6v26h-6Z" fill="#b28c60"/><ellipse cx="32" cy="43" rx="17" ry="15"/><ellipse cx="32" cy="43" rx="8" ry="15"/>',
piping:'<path d="m14 10 39 8-20 33Z" fill="#dbc0d4"/><path d="m28 46 7 4-9 11Z" fill="#a29483"/><path d="M14 10 20 3l31 8 2 7"/>',
'recipe-board':'<rect x="12" y="8" width="42" height="49" rx="4" fill="#eee1c5"/><path d="M21 8v49m7-35h18M28 32h18m-18 10h12"/>',
flowers:'<path d="M32 55V20m0 23L18 26m14 17 15-16"/><circle cx="32" cy="16" r="10" fill="#caa2b8"/><circle cx="17" cy="25" r="8" fill="#e6c174"/><circle cx="48" cy="25" r="8" fill="#caa2b8"/><path d="M22 43h20l-3 17H25Z" fill="#bf8c64"/>',
bell:'<path d="M10 45h44M16 42q0-24 16-24t16 24Z" fill="#d6b475"/><path d="M32 18V9m-6 0h12M8 52h48"/>'};return `<svg viewBox="0 0 64 64" class="upgrade-icon" aria-hidden="true" fill="none" stroke="#688064" stroke-width="2.7" stroke-linejoin="round" stroke-linecap="round">${drawings[id]||drawings.plant}</svg>`}
function shop(){const selected=SHOP.find(u=>u.id===shopPreview)||SHOP.find(u=>groupFor(u)===shopTab)||SHOP[0];shopPreview=selected.id;const owned=progress.owned.includes(selected.id),locked=(progress.served||0)<(selected.unlock||0);modal(`<div class="shop-title-row"><div><span class="eyebrow">TU CAFÉ CRECE CON CADA PEDIDO</span><h2>La tienda de Delfi</h2></div><div class="shop-wallet">${progress.coins} ✦<small>${progress.served} clientes atendidos</small></div></div><div class="shop-tabs">${[['all','Todo'],['tools','Cocina'],['decor','Ambiente'],['pets','Mascotas']].map(([id,n])=>button(n,'shop-tab','tab '+(id===shopTab?'active':''),`data-id="${id}"`)).join('')}</div><div class="shop-showcase"><div class="upgrade-preview preview-${groupFor(selected)}"><span>${shopIcon(selected.id)}</span><b>${esc(selected.name)}</b><small>${owned?'Ya es parte de tu cafetería':'Imaginá este detalle en tu café'}</small></div><div><span class="eyebrow">${groupFor(selected)==='tools'?'MEJORA PARA LOS MINIJUEGOS':'UN DETALLE CON PERSONALIDAD'}</span><h3>${selected.name}</h3><p>${selected.description}</p>${locked?`<p class="unlock-note">Atendé ${selected.unlock} clientes · ${Math.min(progress.served,selected.unlock)}/${selected.unlock}</p>`:''}${owned?(decorIds.includes(selected.id)?button(hasUpgrade(selected.id)?'✓ Activada · guardar':'Activar en el café','equip-upgrade','secondary',`data-id="${selected.id}"`):'<b class="owned-note">Comprada · efecto activo ✓</b>'):button(locked?'Todavía bloqueada':progress.coins<selected.price?`Te faltan ${selected.price-progress.coins} ✦`:`Comprar por ${selected.price} ✦`,'buy-upgrade','primary',`data-id="${selected.id}" ${locked||progress.coins<selected.price?'disabled':''}`)}</div></div><div class="shop-grid">${SHOP.filter(u=>shopTab==='all'||groupFor(u)===shopTab).map(u=>`<button class="shop-card ${u.id===selected.id?'chosen':''}" data-action="shop-preview" data-id="${u.id}"><span class="shop-art">${shopIcon(u.id)}</span><strong>${u.name}</strong><small>${progress.owned.includes(u.id)?(decorIds.includes(u.id)&&!hasUpgrade(u.id)?'Guardada':'Activa ✓'):(u.unlock||0)>progress.served?'Con '+u.unlock+' clientes':u.price+' ✦'}</small></button>`).join('')}</div><p class="shop-footnote">Las compras son permanentes. Podés guardar la decoración y volver a activarla sin pagar. La tienda pausa la espera del cliente.</p>`,'shop-modal upgraded-shop')}
function stopMini(){cancelAnimationFrame(miniFrame);miniFrame=0;mini=null}
const challengeClose=closeModal;
closeModal=function(cancel=true){if(cancel)stopMini();challengeClose(cancel)};
const challengeHome=goHome;
goHome=function(){stopMini();state.customerClock=null;challengeHome()};
const taskTitles={assemble:'Ingredientes en orden',trace:'Dale forma a la masa',frost:'Dibujá el frosting',stir:'Mezclá en círculos',pour:'Serví la cantidad justa',heat:'Controlá la cocción',slice:'Cortá por las guías',arrange:'Decorá con pulso firme'};
const taskHelp={assemble:'Memorizá el orden. Arrastrá cada ingrediente al bol. No alcanza con tocarlo.',trace:'Mantené presionado y seguí los puntos dorados de la espiral, en orden.',frost:'Elegí el sabor del ticket. Después mantené presionado y trazá la crema.',arrange:'Mantené presionado y recorré la decoración siguiendo el punto dorado.',stir:'Mantené presionado y girá alrededor del bol, en sentido horario. Completá tres vueltas.',pour:'Mantené presionado para verter. Soltá cuando el líquido llegue a la marca dorada.',heat:'Mantené presionado para subir el fuego; soltá para bajar. Sostené la temperatura en verde durante 8 segundos.',slice:'Mantené presionado y cortá desde arriba hasta abajo por cada línea dorada.'};
prepStart=function(id){if(state.serving||state.scene!=='work')return;if(state.tray.length>=4)return toast('La bandeja está llena.');if(!item(id))return;stopMini();state.prep={id,step:0,scores:[],frosting:null,quality:100,tasks:SkillRules.tasks(item(id))};renderSkill()};
function renderSkill(){stopMini();const p=state.prep;if(!p)return;const kind=p.tasks[p.step],product=item(p.id);modal(`<div class="skill-heading"><div><span class="eyebrow">COCINA CON LAS MANOS · ${p.step+1}/${p.tasks.length}</span><h2>${product.name}</h2></div><span class="quality-badge">${p.scores.length?'Calidad '+Math.round(p.scores.reduce((a,b)=>a+b,0)/p.scores.length):'Preparación nueva'}</span></div><div class="skill-steps">${p.tasks.map((t,i)=>`<span class="${i===p.step?'active':''}">${i<p.step?'✓ ':''}${taskTitles[t]}</span>`).join('')}</div><div class="customer-watch" data-mood="${mood()}">${watchHtml()}</div><h3>${taskTitles[kind]}</h3><p class="skill-help">${taskHelp[kind]}</p>${kind==='frost'?`<div class="skill-frostings">${FROSTINGS.map(f=>button(f.name,'skill-frost','secondary',`data-id="${f.id}"`)).join('')}</div>`:''}<canvas id="skill-canvas" width="800" height="390" tabindex="0" aria-label="${taskHelp[kind]}" role="application"></canvas><div class="skill-bottom"><span id="skill-feedback" aria-live="polite">${kind==='assemble'?'Recordá el orden antes de que se oculte…':kind==='frost'?'Primero elegí el frosting.':'Cuando quieras, empezá.'}</span><span id="skill-result"></span></div><details class="keyboard-help"><summary>Controles de teclado</summary><p>Ingredientes: teclas 1–5 para elegir y Enter para colocar. Trazos y cortes: flechas para mover la herramienta, Espacio para apoyar/levantar. Mezcla: flechas alrededor del círculo. Llenado y fuego: mantené Espacio y soltá.</p></details>`,'challenge-modal');
 const canvas=$('#skill-canvas');mini={kind,canvas,ctx:canvas.getContext('2d'),score:100,done:false,down:false,last:null,time:0,started:false,lastAt:performance.now(),revealAt:performance.now()+5000,progress:0,fill:0,temp:50,good:0,turn:0,cuts:0,keyboard:{x:400,y:220},badAt:0};
 if(kind==='assemble'){mini.ingredients=SkillRules.ingredients(product);while(mini.ingredients.length<3)mini.ingredients.push('toque final');mini.cards=[...mini.ingredients,'sal extra','salsa de tomate'].map((label,id)=>({label,id})).sort(()=>Math.random()-.5)}
 if(['trace','frost','arrange'].includes(kind)){mini.path=Array.from({length:42},(_,i)=>{const a=i/41*Math.PI*4,r=25+i/41*120;return {x:400+Math.cos(a)*r,y:205+Math.sin(a)*r}})}
 canvas.addEventListener('pointerdown',miniDown);canvas.addEventListener('pointermove',miniMove);canvas.addEventListener('pointerup',miniUp);canvas.addEventListener('pointercancel',()=>{if(mini){mini.down=false;mini.drag=null;mini.last=null}});canvas.addEventListener('keydown',miniKeyDown);canvas.addEventListener('keyup',miniKeyUp);canvas.addEventListener('blur',()=>{if(mini){mini.down=false;mini.last=null;mini.drag=null}});miniFrame=requestAnimationFrame(drawSkill);
}
function point(e){const r=mini.canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*800/r.width,y:(e.clientY-r.top)*390/r.height}}
function miniDown(e){if(!mini||mini.done)return;mini.canvas.focus();mini.canvas.setPointerCapture(e.pointerId);const p=point(e);mini.down=true;mini.last=p;mini.started=true;if(mini.kind==='assemble')mini.drag=mini.cards.find((c,i)=>p.x>=30+i*152&&p.x<=170+i*152&&p.y>=34&&p.y<=106);if(mini.kind==='slice'){mini.cutStart=p;mini.cutDeviation=0;}miniSample(p);e.preventDefault()}
function miniMove(e){if(!mini||mini.done)return;miniSample(point(e))}
function miniSample(p){const g=mini;if(!g||!g.down)return;if(g.kind==='assemble'){g.cursor=p;return}if(g.kind==='slice'&&g.cutStart)g.cutDeviation=Math.max(g.cutDeviation||0,Math.abs(p.x-(270+g.cuts*130)));if(['trace','frost','arrange'].includes(g.kind)){if(g.kind==='frost'&&!state.prep.frosting)return;const target=g.path[g.progress],dist=Math.hypot(p.x-target.x,p.y-target.y),tol=hasUpgrade('piping')?29:21;if(dist<tol){g.progress++;if(g.progress===g.path.length){finishSkill(g.score);return}}else if(dist>tol+25)skillMistake('Reencontrá el punto dorado.',2)}if(g.kind==='stir'){const r=Math.hypot(p.x-400,p.y-205),tol=hasUpgrade('whisk')?52:30;if(Math.abs(r-100)<=tol){const angle=Math.atan2(p.y-205,p.x-400);if(g.angle!==undefined){let delta=angle-g.angle;while(delta>Math.PI)delta-=Math.PI*2;while(delta<-Math.PI)delta+=Math.PI*2;if(delta>0&&delta<.65)g.turn+=delta;else if(delta<-.12)skillMistake('Giramos en sentido horario.',2)}g.angle=angle;if(g.turn>=Math.PI*6)finishSkill(g.score)}else{g.angle=undefined;skillMistake('Mantené la cuchara dentro del bol.',2)}}g.last=p}
function miniUp(e){if(!mini||mini.done)return;releaseMini(point(e))}
function releaseMini(p){const g=mini;if(!g||!g.down)return;g.down=false;if(g.kind==='assemble'&&g.drag){if(Math.hypot(p.x-400,(p.y-256)*1.3)<115){if(g.drag.label===g.ingredients[g.progress]){g.progress++;$('#skill-feedback').textContent='¡Bien! '+g.progress+'/3 ingredientes.';if(g.progress===3)finishSkill(g.score)}else{g.score=Math.max(0,g.score-18);$('#skill-feedback').textContent='Ese no iba ahora. −18 de calidad.'}}g.drag=null}if(g.kind==='pour'&&g.fill>1)finishSkill(SkillRules.pour(g.fill,68,hasUpgrade('grinder')?6:0));if(g.kind==='slice'&&g.cutStart){const x=270+g.cuts*130,err=Math.max(Math.abs(g.cutStart.x-x),Math.abs(p.x-x),g.cutDeviation||0);if(g.cutStart.y<130&&p.y>295&&err<36){g.score=Math.max(0,g.score-Math.max(0,err-10));g.cuts++;if(g.cuts===3)finishSkill(g.score)}else skillMistake('Cortá de arriba hacia abajo sobre la guía.',10);g.cutStart=null}g.last=null;g.angle=undefined}
function skillMistake(message,loss){if(!mini||performance.now()-mini.badAt<350)return;mini.badAt=performance.now();mini.score=Math.max(0,mini.score-loss);$('#skill-feedback').textContent=message}
function finishSkill(score){const g=mini;if(!g||g.done)return;g.done=true;g.down=false;cancelAnimationFrame(miniFrame);state.prep.scores.push(Math.round(SkillRules.clamp(score)));$('#skill-feedback').textContent=`${Math.round(score)>=85?'¡Qué buen pulso!':Math.round(score)>=60?'Salió bien, pero se puede afinar.':'Este paso salió flojo: el cliente lo va a notar.'} ${Math.round(score)}/100`;$('#skill-result').innerHTML=button(state.prep.step===state.prep.tasks.length-1?'Pasar a la bandeja →':'Siguiente paso →','skill-next');drawSkill(performance.now(),true)}
function miniKeyDown(e){if(!mini||mini.done)return;const g=mini;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' ','Enter','1','2','3','4','5'].includes(e.key))e.preventDefault();if(g.kind==='assemble'){if(/^[1-5]$/.test(e.key)){g.drag=g.cards[Number(e.key)-1];$('#skill-feedback').textContent='Elegiste '+g.drag.label+'. Enter para colocarlo.'}if(e.key==='Enter'&&g.drag){g.down=true;releaseMini({x:400,y:256})}return}if(e.key===' '&&!e.repeat){g.started=true;if(['pour','heat'].includes(g.kind))g.down=true;else{if(g.down){releaseMini(g.keyboard)}else{g.down=true;g.cutStart={...g.keyboard};g.cutDeviation=0;miniSample(g.keyboard)}}}if(e.key.startsWith('Arrow')){const moves={ArrowLeft:[-10,0],ArrowRight:[10,0],ArrowUp:[0,-10],ArrowDown:[0,10]},d=moves[e.key];g.keyboard.x=SkillRules.clamp(g.keyboard.x+d[0],0,800);g.keyboard.y=SkillRules.clamp(g.keyboard.y+d[1],0,390);miniSample({...g.keyboard})}}
function miniKeyUp(e){if(e.key===' '&&mini&&['pour','heat'].includes(mini.kind)){e.preventDefault();releaseMini(mini.keyboard)}}
function drawSkill(now,once=false){const g=mini;if(!g)return;const c=g.ctx,dt=Math.min(.05,Math.max(0,(now-g.lastAt)/1000));g.lastAt=now;if(!g.done&&g.started&&!document.hidden){if(g.kind==='pour'&&g.down){g.fill+=dt*22;if(g.fill>=102){finishSkill(0);return}}if(g.kind==='heat'){g.time+=dt;g.temp=SkillRules.clamp(g.temp+dt*(g.down?29:-13));const lo=hasUpgrade('oven')?45:54,hi=hasUpgrade('oven')?76:67;if(g.temp>=lo&&g.temp<=hi)g.good+=dt;if(g.time>=8){finishSkill(g.good/8*100);return}}}
 c.clearRect(0,0,800,390);c.fillStyle='#f1e4cf';c.fillRect(0,0,800,390);c.fillStyle='#e6d1b1';for(let y=0;y<390;y+=48)c.fillRect(0,y,800,2);c.textAlign='center';c.font='16px Georgia';
 const circle=(x,y,r,color)=>{c.fillStyle=color;c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fill()};
 if(g.kind==='assemble'){g.cards.forEach((card,i)=>{c.fillStyle=g.drag===card?'#cfdfc5':'#fff9ec';c.fillRect(30+i*152,34,140,72);c.fillStyle='#445645';c.font='12px sans-serif';const words=card.label.split(' ');let lines=[''];for(const w of words){if((lines.at(-1)+w).length>19)lines.push('');lines[lines.length-1]+=w+' '}lines.slice(0,3).forEach((l,j)=>c.fillText(l,100+i*152,53+j*16));c.fillText(i+1,100+i*152,121)});circle(400,256,97,'#b5c8ad');circle(400,246,78,'#fff7e5');c.fillStyle='#475b45';c.font='18px Georgia';c.fillText('BOL · '+g.progress+'/3',400,253);c.font='14px sans-serif';c.fillText(now<g.revealAt||hasUpgrade('recipe-board')?'Orden: '+g.ingredients.join(' → '):'¿Recordás el orden? Arrastrá el siguiente.',400,365);if(g.drag&&g.cursor){circle(g.cursor.x,g.cursor.y,27,'#b88550');c.fillStyle='#fff';c.font='11px sans-serif';c.fillText(g.drag.label.slice(0,22),g.cursor.x,g.cursor.y)}}
 if(['trace','frost','arrange'].includes(g.kind)){circle(400,205,170,'#dab586');circle(400,205,157,'#e9cfa4');c.lineWidth=8;c.strokeStyle='#b8916044';c.beginPath();g.path.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.stroke();c.strokeStyle=g.kind==='frost'?(FROSTINGS.find(f=>f.id===state.prep.frosting)?.color||'#fff9e9'):'#966641';c.lineWidth=13;c.lineCap='round';c.beginPath();g.path.slice(0,g.progress).forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.stroke();if(!g.done){const p=g.path[g.progress];circle(p.x,p.y,11,'#b7862d');circle(p.x,p.y,5,'#fff')}c.fillStyle='#4d5d46';c.font='15px sans-serif';c.fillText(Math.round(g.progress/g.path.length*100)+' % del trazo',400,380)}
 if(g.kind==='stir'){circle(400,205,150,'#a6b99b');circle(400,205,130,'#e4c391');c.strokeStyle='#a16b41';c.lineWidth=7;c.beginPath();c.arc(400,205,100,0,Math.PI*2);c.stroke();c.strokeStyle='#4c775a';c.lineWidth=12;c.beginPath();c.arc(400,205,143,-Math.PI/2,-Math.PI/2+g.turn/3);c.stroke();const p=g.last||{x:500,y:205};c.strokeStyle='#86603f';c.lineWidth=13;c.beginPath();c.moveTo(p.x,p.y);c.lineTo(p.x+28,p.y-65);c.stroke();circle(p.x,p.y,15,'#cda879');c.fillStyle='#445844';c.font='18px Georgia';c.fillText((g.turn/(Math.PI*2)).toFixed(1)+' / 3 vueltas ↻',400,378)}
 if(g.kind==='pour'){c.fillStyle='#fff9e9';c.fillRect(302,80,196,240);c.fillStyle='#ac7650';c.fillRect(310,312-g.fill*2.25,180,g.fill*2.25);c.strokeStyle='#b68932';c.lineWidth=5;c.setLineDash([10,7]);c.beginPath();c.moveTo(287,312-68*2.25);c.lineTo(515,312-68*2.25);c.stroke();c.setLineDash([]);c.fillStyle='#435743';c.font='18px Georgia';c.fillText('Soltá al llegar a la marca · '+Math.round(g.fill)+' %',400,358);if(g.down){c.fillStyle='#ac7650';c.fillRect(392,10,16,Math.max(0,302-g.fill*2.25))}}
 if(g.kind==='heat'){const lo=hasUpgrade('oven')?45:54,hi=hasUpgrade('oven')?76:67;c.fillStyle='#d4b88e';c.fillRect(100,150,600,65);c.fillStyle='#a2bb90';c.fillRect(100+lo*6,150,(hi-lo)*6,65);c.fillStyle='#77543b';c.fillRect(96+g.temp*6,139,8,88);c.fillStyle='#435743';c.font='23px Georgia';c.fillText(Math.round(g.temp)+'° · '+Math.max(0,8-g.time).toFixed(1)+' s',400,105);c.font='18px Georgia';c.fillText(g.down?'Fuego encendido ↑':'Bajando el fuego ↓',400,280);c.fillText('Tiempo en el punto ideal: '+g.good.toFixed(1)+' s',400,323)}
 if(g.kind==='slice'){c.fillStyle='#c79560';c.fillRect(190,115,420,190);c.fillStyle='#edc892';c.fillRect(195,120,410,175);for(let i=0;i<3;i++){c.strokeStyle=i<g.cuts?'#75462f':i===g.cuts?'#b78829':'#fff8';c.lineWidth=i<g.cuts?9:4;c.setLineDash(i<g.cuts?[]:[9,8]);c.beginPath();c.moveTo(270+i*130,95);c.lineTo(270+i*130,326);c.stroke()}c.setLineDash([]);c.fillStyle='#445744';c.font='18px Georgia';c.fillText(g.cuts+' / 3 cortes · de arriba hacia abajo ↓',400,365)}
 if(document.activeElement===g.canvas&&g.kind!=='assemble'){c.strokeStyle='#3f7059';c.lineWidth=2;c.strokeRect(g.keyboard.x-7,g.keyboard.y-7,14,14)}
 if(!once&&!g.done)miniFrame=requestAnimationFrame(drawSkill)
}
window.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;if(!['shop-tab','shop-preview','buy-upgrade','equip-upgrade','skill-frost','skill-next','soothe'].includes(a))return;e.preventDefault();e.stopImmediatePropagation();switch(a){case 'shop-tab':shopTab=b.dataset.id;shopPreview=null;shop();break;case 'shop-preview':shopPreview=b.dataset.id;shop();break;case 'buy-upgrade':{const r=SkillRules.buy(progress,SHOP,b.dataset.id);if(r.ok){save();render();shop();toast('¡'+r.item.name+' ya es parte del café!')}else toast(r.reason);break}case 'equip-upgrade':{const id=b.dataset.id;if(!decorIds.includes(id)||!progress.owned.includes(id))break;progress.disabledDecor=hasUpgrade(id)?[...progress.disabledDecor,id]:progress.disabledDecor.filter(x=>x!==id);save();render();shop();break}case 'soothe':if(state.customerClock&&!state.customerClock.soothed&&!state.serving){state.customerClock.soothed=true;state.customerClock.left=Math.min(state.customerClock.total,state.customerClock.left+12);render();toast('“Gracias por avisar, espero un poquito más.”')}break;case 'skill-frost':if(state.prep&&mini&&!mini.done){state.prep.frosting=b.dataset.id;document.querySelectorAll('.skill-frostings button').forEach(el=>el.classList.toggle('chosen',el.dataset.id===b.dataset.id));$('#skill-feedback').textContent='Ahora trazá la crema.'}break;case 'skill-next':{if(!state.prep||!mini?.done)break;const p=state.prep;p.step++;if(p.step>=p.tasks.length){p.quality=Math.round(p.scores.reduce((a,b)=>a+b,0)/p.scores.length);state.tray.push({id:p.id,quality:p.quality,...(p.frosting?{frosting:p.frosting}:{})});state.prep=null;closeModal();render();toast('Producto listo · calidad '+p.quality+'/100')}else renderSkill();break}}},true);
document.addEventListener('pointermove',e=>{const stage=e.target.closest('.customer-stage');if(stage){const r=stage.getBoundingClientRect();stage.style.setProperty('--attention',((e.clientX-r.left)/r.width-.5)*5+'deg')}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&mini){mini.down=false;mini.drag=null;mini.last=null;mini.angle=undefined}});
const challengeHelp=help;
help=function(){challengeHelp();$('.modal').insertAdjacentHTML('beforeend','<h3>Nuevo desafío de cocina</h3><p>Arrastrá, trazá, mezclá y controlá el punto. Los productos guardan su calidad. La paciencia baja durante la preparación; los errores de entrega cuestan 8 segundos y bajan la valoración. La tienda y el recetario pausan el reloj. Las mejoras de cocina ayudan en minijuegos concretos.</p>')};
const previousCustomerSprite=sprite;
sprite=function(index,cls='',name=''){if(index<4||index>8)return previousCustomerSprite(index,cls,name);return `<span class="actor-sprite art-expression ${cls}" style="--person:${index-4}" data-sprite="${index}" role="img" aria-label="${esc(name)}"></span>`};
save();render();
