'use strict';
const {MENU,FROSTINGS,validateOrder}=CafeData;
const $=s=>document.querySelector(s), item=id=>MENU.find(x=>x.id===id), money=n=>`${n} ✦`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const defaults={coins:0,served:0,visits:0,day:1,best:0,decor:false};
let progress;try{progress={...defaults,...JSON.parse(localStorage.getItem('delfi-cafe-v1')||'{}')}}catch{progress={...defaults}}
let state={scene:'welcome',seat:null,cart:[],category:'dulce',orders:[],tray:[],delivery:'here',completed:0,earned:0,prep:null,meal:[],sound:false},pending=null,bakeTimer=null,audio=null,musicTimer=null,toastTimer;
function save(){try{localStorage.setItem('delfi-cafe-v1',JSON.stringify(progress))}catch{toast('El navegador no pudo guardar el progreso. Esta partida sigue funcionando.')}}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4000)}
function tone(f=600,d=.1,vol=.035){if(!state.sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();let o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch{}}
function toggleSound(){state.sound=!state.sound;clearInterval(musicTimer);if(state.sound){tone(523,.7);let n=0;musicTimer=setInterval(()=>{tone([261.6,329.6,392,493.9,440,329.6,293.7,392][n++%8],2,.016)},1600)}render()}
function food(id,frosting='cream',large=false){const p=item(id),color=FROSTINGS.find(f=>f.id===frosting)?.color||'#fff3da';let art='';
if(p.art==='roll')art=`<ellipse cx="60" cy="88" rx="43" ry="10" fill="#d8c4a6"/><path d="M22 60q0-32 39-33t38 33v15q-4 24-39 22T22 75Z" fill="#b87943" stroke="#8c522f" stroke-width="2"/><ellipse cx="60" cy="56" rx="38" ry="29" fill="#e8b675"/><path d="M59 58c-15-13 9-27 20-11 16 24-25 38-39 14-14-27 27-42 46-23" fill="none" stroke="#955630" stroke-width="6" stroke-linecap="round"/><path d="M28 45q13-18 29-9t27 2M29 62q13 11 18 3t15 7 26-12" fill="none" stroke="${color}" opacity="${frosting==='none'?0:1}" stroke-width="8" stroke-linecap="round"/>${id==='apple-roll'?'<path d="M34 39l7-8 9 5-4 8M70 72l8-8 9 6-5 8" fill="#de9860"/>':''}`;
else if(['coffee','tea'].includes(p.art))art=`<ellipse cx="59" cy="92" rx="44" ry="10" fill="#ddd0ba"/><path d="M82 48q35-4 21 27-10 11-22 0" fill="none" stroke="#bdc5aa" stroke-width="9"/><path d="M25 41h61v34q-3 23-30 23T25 75Z" fill="${p.art==='tea'?'#cdc4de':'#91a28a'}"/><ellipse cx="55" cy="42" rx="30" ry="11" fill="${p.art==='tea'?'#ba9061':'#895c42'}"/><path d="M54 48q-24-15-9-14 9 0 9 6 2-12 12-6 10 5-12 14" fill="#f9e2bf"/><path d="M40 24q-8-8 0-16M60 22q8-8 0-16" stroke="#fff7e8" stroke-width="3" fill="none"/>`;
else if(p.art==='cat')art='<path d="M25 46l-2-25 25 14q12-5 25 0l22-14-1 28q20 44-33 49-52-1-36-52" fill="#d9a063" stroke="#a97646" stroke-width="3"/><path d="M41 60v6m37-6v6M52 74q8 10 16 0m-34-3-12-2m62 2 13-2" stroke="#774d39" stroke-width="3" stroke-linecap="round" fill="none"/><path d="M56 68h9l-5 6Z" fill="#c78078"/>';
else if(p.art==='sandwich')art=`<path d="M20 76L58 22l47 59-53 21Z" fill="#c48b52"/><path d="M23 64L58 14l43 56-49 19Z" fill="#efcc91" stroke="#b97c43" stroke-width="3"/><path d="M26 75l28 15 42-15" fill="none" stroke="${id==='toast'?'#edb892':'#819556'}" stroke-width="9"/><path d="M43 53l17-21m0 31 12-18" stroke="#d6a765" stroke-width="3"/>`;
else if(p.art==='lemonade')art='<path d="M29 24h59L80 104H37Z" fill="#dcebc8" stroke="#c0cdb0" stroke-width="3"/><path d="M33 47h51l-6 53H39Z" fill="#e2d57c"/><path d="M65 73 83 4" stroke="#b78380" stroke-width="5"/><circle cx="35" cy="45" r="17" fill="#f6dc68" stroke="#fff3a1" stroke-width="4"/><path d="M49 76q-13-28 10-16 10-20 15-1" fill="#7f9a63"/>';
else if(p.art==='board')art='<ellipse cx="60" cy="68" rx="54" ry="36" fill="#bd8b57"/><path d="M18 62 47 38 57 76Z" fill="#f3dba0"/><path d="M64 40h31v25H64Z" fill="#e3d8b4"/><path d="M70 42l9 18m5-18-10 12" stroke="#84947e" stroke-width="3"/><circle cx="73" cy="79" r="14" fill="#fff1d6"/><circle cx="29" cy="83" r="6" fill="#846179"/><circle cx="40" cy="83" r="6" fill="#8d6882"/><circle cx="35" cy="74" r="6" fill="#74566d"/>';
else if(p.art==='scone')art='<path d="M23 57 62 27l39 36-7 30-65-2Z" fill="#ba824f"/><path d="M23 57 62 27l39 36-49 15Z" fill="#e5b979"/><path d="M42 48l9-4m11 14 7-5m-21 9 4-6" stroke="#809263" stroke-width="4"/>';
else if(p.art==='fruit'||p.art==='icecream')art='<path d="M20 65h80Q92 103 60 105 30 98 20 65Z" fill="#cbd5bc"/><circle cx="40" cy="58" r="20" fill="#e8afaa"/><circle cx="78" cy="57" r="20" fill="#ddc094"/><circle cx="59" cy="36" r="21" fill="#eee1b9"/><path d="M87 47 98 4" stroke="#ba8e5b" stroke-width="8"/>';
else if(p.art==='croissant')art='<path d="M12 87Q8 47 41 40Q56 18 76 40q36 6 34 47L91 74 75 81 57 69 39 83 24 72Z" fill="#dca866" stroke="#a5703e" stroke-width="3"/><path d="M41 40 39 79m37-39-1 38M58 32 57 66" stroke="#b17a43" stroke-width="3"/>';
else if(p.art==='mousse'||p.art==='flan')art=`<path d="M29 58h64l-12 36H42Z" fill="#d6c9b8"/><ellipse cx="61" cy="58" rx="32" ry="17" fill="${id.includes('lemon')?'#eddfa9':'#855643'}"/><path d="M42 53q-3-16 14-17-4-18 9-12 20 5 9 15 17 10 4 16Z" fill="#ffedd7"/><circle cx="62" cy="25" r="5" fill="#9b4e52"/>`;
else if(p.art==='cookies'||p.art==='alfajor')art=`<ellipse cx="61" cy="72" rx="40" ry="26" fill="${p.art==='alfajor'?'#613f32':'#be824d'}"/><ellipse cx="61" cy="60" rx="40" ry="25" fill="${p.art==='alfajor'?'#81543b':'#e2b577'}"/><path d="M33 54l55 14m-47-24 34 35m-47-16 56-8" stroke="${p.art==='alfajor'?'#c69f69':'#f3d59d'}" stroke-width="4"/>`;
else art=`<path d="M23 55 65 23 100 48v41L55 104 23 87Z" fill="${p.art==='brownie'?'#674532':'#e3c395'}"/><path d="M23 66 56 82l44-19v10L55 92 23 77Z" fill="#fff0d7"/><path d="M23 55 65 23l35 25-45 23Z" fill="${id==='cheesecake'?'#a85665':p.art==='brownie'?'#81513a':'#f5e4c5'}"/>${id==='cheesecake'?'<circle cx="67" cy="37" r="8" fill="#7c394f"/><circle cx="79" cy="44" r="6" fill="#c36972"/>':'<path d="M47 48q20-17 34-5" fill="none" stroke="#b18753" stroke-width="4"/>'}`;
return `<svg class="food-art ${large?'large':''}" viewBox="0 0 120 120" role="img" aria-label="${esc(p.name)}"><ellipse cx="60" cy="99" rx="50" ry="10" fill="#614836" opacity=".08"/>${art}</svg>`}
function button(label,action,cls='primary',extra=''){return `<button class="${cls}" data-action="${action}" ${extra}>${label}</button>`}
function header(){return `<header class="topbar"><button class="brand" data-action="home" aria-label="Volver a la entrada"><img src="assets/icon.svg" alt=""><span>Delfi<small>CANELA & CAFÉ</small></span></button><div class="top-center">un pequeño lugar para estar bien</div><nav><span class="coin" title="Monedas del juego">${money(progress.coins)}</span>${button(state.sound?'♫':'♪','sound','icon-button',`aria-label="${state.sound?'Desactivar':'Activar'} música" title="Música suave"`)}${button('<svg width="15" height="15" viewBox="0 0 16 16" aria-hidden="true"><path d="M6 2H2v4m8-4h4v4M2 10v4h4m4 0h4v-4" fill="none" stroke="currentColor" stroke-width="1.5"/></svg>','fullscreen','icon-button','aria-label="Pantalla completa" title="Pantalla completa"')}${button('?','help','icon-button','aria-label="Cómo jugar"')}</nav></header>`}
function dialogue(name,msg,actions=''){return `<section class="dialogue"><div class="speaker-avatar"><img src="assets/welcome.webp" alt="Delfi"></div><div class="speech"><span class="eyebrow">${name}</span><p>${msg}</p></div><div class="dialogue-actions">${actions}</div></section>`}
function welcome(){return `<main class="welcome scene"><div class="scene-image exterior"></div><div class="welcome-shade"></div><div class="hanging-tag"><span class="tiny-star">✧</span> ABIERTO · PASÁ SIN APURO</div><div class="welcome-title"><span class="eyebrow">BIENVENIDO A</span><h1>Un ratito<br>en <em>Delfi.</em></h1><p>El aroma a canela te trajo hasta acá.<br>Lo lindo es que podés quedarte.</p><div class="specialty">${food('roll')}<span>Hechos con amor<small>nuestros rolls de canela</small></span></div></div><div class="scene-caption">Una cafetería, muchas pequeñas historias.</div><div class="ambient particles"><i></i><i></i><i></i><i></i></div></main>${dialogue('DELFI · TU ANFITRIONA','¡Hola! Qué lindo que viniste. ¿Querés tomar/comer algo o trabajar conmigo?',button('☕ &nbsp; Quiero merendar','guest')+button('♧ &nbsp; Quiero trabajar','work','secondary'))}<footer>UN JUEGO PARA DISFRUTAR SIN APURO <span>✧</span> INSPIRADO EN DELFI, HECHO CON CARIÑO</footer>`}
const seats=[{id:0,name:'Junto a la ventana',x:23,y:59},{id:1,name:'Rincón de las plantas',x:75,y:60},{id:2,name:'Mesa del centro',x:49,y:78},{id:3,name:'En la barra',x:58,y:41}];
function guest(){let seated=state.seat!==null,meal=state.scene==='meal',waiting=state.scene==='waiting';return `<main class="scene lounge"><div class="scene-image interior"></div><div class="room-vignette"></div><div class="scene-label"><span class="eyebrow">${meal?'TU MOMENTO':seated?'PONETE CÓMODO':'EL SALÓN'}</span><h2>${seated?seats[state.seat].name:'Elegí tu lugar favorito'}</h2></div>${!seated?seats.map(s=>`<button class="seat-hotspot" style="left:${s.x}%;top:${s.y}%" data-action="seat" data-id="${s.id}"><span>＋</span>${s.name}</button>`).join(''):''}${waiting?'<div class="waiting-card"><div class="steam">♨</div><h3>Delfi está preparando tu pedido</h3><p>Ya sale algo rico para vos…</p></div>':''}${meal?`<div class="table-service"><span class="eyebrow">SERVIDO CON CARIÑO · HACÉ CLIC PARA DISFRUTAR</span><div class="served-food">${state.meal.map((p,i)=>`<button data-action="eat" data-index="${i}" class="served-item">${food(p.id,p.frosting,true)}<span>${item(p.id).name}</span></button>`).join('')}</div></div>`:''}${progress.decor?'<div class="extra-plant" title="Tu planta para la cafetería">🪴</div>':''}</main>${dialogue('DELFI',waiting?'Ahora te lo traigo. Mientras tanto, disfrutá el lugar.':meal?'Acá tenés, recién preparado. Espero que te guste tanto como a mí prepararlo.':seated?'¿Te acerco el menú? Los rolls de canela son la especialidad de la casa.':'Sentate donde más te guste. Yo te acompaño enseguida.',!seated?button('Volver','home','text-button'):waiting?'':meal?button('Gracias, Delfi ♡','finish-meal','secondary'):button('Ver el menú →','menu'))}`}
function ticketHtml(order){return `<div class="ticket-head"><span>PEDIDO ${String(order.number).padStart(2,'0')}</span><span>${order.delivery==='takeaway'?'↗ PARA LLEVAR':'⌂ PARA MESA'}</span></div><h3>${order.name}</h3><p class="customer-quote">“${order.quote}”</p><ul class="ticket-list">${order.items.map(p=>`<li><span class="check-dot ${state.tray.some(a=>a.id===p.id&&a.frosting===p.frosting)?'checked':''}"></span><div>${item(p.id).name}${p.frosting?`<small>Frosting: ${FROSTINGS.find(f=>f.id===p.frosting).name}</small>`:''}</div></li>`).join('')}</ul>`}
function work(){const o=state.orders[0];return `<main class="work-layout"><section class="kitchen"><div class="kitchen-backdrop"></div><div class="work-heading"><span class="eyebrow">DEL OTRO LADO DEL MOSTRADOR</span><h2>Un pedido, una sonrisa.</h2><p>Turno ${progress.day} · ${state.completed}/5 clientes atendidos</p></div><div class="station-grid"><button class="station" data-action="catalog" data-category="dulce"><span class="station-picture pastry">${food('roll','lavender',true)}${food('cat-cookie')}</span><span class="station-number">01</span><strong>Pastelería</strong><small>Masa, canela y cosas lindas</small></button><button class="station" data-action="catalog" data-category="salado"><span class="station-picture">${food('cheese-scone',null,true)}</span><span class="station-number">02</span><strong>Cocina salada</strong><small>Algo calentito y casero</small></button><button class="station" data-action="catalog" data-category="bebida"><span class="station-picture">${food('latte',null,true)}</span><span class="station-number">03</span><strong>Barra de café</strong><small>El aroma de una buena pausa</small></button></div><div class="tray"><div class="tray-title"><span class="eyebrow">TU BANDEJA</span><small>${state.tray.length}/4 productos · clic para retirar</small></div><div class="tray-items">${state.tray.length?state.tray.map((p,i)=>`<button class="tray-item" data-action="remove-tray" data-index="${i}" title="Retirar ${esc(item(p.id).name)}">${food(p.id,p.frosting)}<span>${item(p.id).name}${p.frosting?`<small>${FROSTINGS.find(f=>f.id===p.frosting).name}</small>`:''}</span><b>×</b></button>`).join(''):'<p class="empty-tray">Todo empieza con un ingrediente y un poquito de cariño.<br><small>Elegí una estación de arriba para preparar el pedido.</small></p>'}</div></div></section><aside class="order-board"><div class="shift-label"><span class="status-dot"></span> ATENDIENDO · ${money(state.earned)} ESTE TURNO</div><article class="ticket">${ticketHtml(o)}<div class="ticket-tear"></div></article><span class="eyebrow">PRESENTACIÓN</span><div class="packaging">${button('⌂ Plato','pack','pack-option '+(state.delivery==='here'?'selected':''),'data-id="here"')}${button('↗ Caja','pack','pack-option '+(state.delivery==='takeaway'?'selected':''),'data-id="takeaway"')}</div>${button('Entregar con cariño →','serve','primary serve-button')}<p class="order-hint">No hay reloj. Revisá el ticket y disfrutá preparando cada cosa.</p></aside></main>${dialogue('DELFI','Estoy acá si necesitás una mano. Primero mirá el pedido y después elegí una estación.',button('Libro de recetas','recipes','secondary')+button('Salir del turno','leave-shift','text-button'))}`}
function summary(){return `<main class="scene lounge"><div class="scene-image interior"></div><div class="room-vignette"></div><section class="end-card"><span class="eyebrow">BAJAMOS UN POQUITO LA PERSIANA</span><h1>Qué lindo equipo<br><em>hacemos.</em></h1><p>Cinco pedidos, cinco pequeñas alegrías.<br>Gracias por compartir este turno conmigo.</p><div class="end-stats"><div><b>5</b><span>sonrisas</span></div><div><b>${state.earned} ✦</b><span>monedas ganadas</span></div></div>${button('Otro turno →','work')}${button('Sentarme a merendar','guest','secondary')}${!progress.decor?button('Regalar una planta · 60 ✦','decor','text-button'):'<p>Tu planta ya tiene su rincón en la cafetería. 🪴</p>'}</section></main>${dialogue('DELFI','Las cosas hechas con cariño siempre se notan. ♡',button('Volver a la entrada','home','text-button'))}`}
function render(){const app=$('#app');app.innerHTML=header()+({welcome:welcome,guest,waiting:guest,meal:guest,work,summary}[state.scene]||welcome)();document.body.dataset.scene=state.scene}
function modal(html,cls=''){closeModal(false);$('#modal-root').innerHTML=`<div class="modal-backdrop"><section class="modal ${cls}" role="dialog" aria-modal="true" aria-label="${cls==='menu-modal'?'Menú de la cafetería':cls==='prep-modal'?'Preparación del pedido':'Cafetería de Delfi'}" tabindex="-1">${button('×','close','close-button','aria-label="Cerrar"')}${html}</section></div>`;$('.modal').focus()}
function closeModal(cancel=true){if(cancel&&state.prep){state.prep=null;clearInterval(bakeTimer)}$('#modal-root').innerHTML=''}
function tabs(){return `<div class="tabs" role="group" aria-label="Categoría">${[['dulce','Dulces'],['salado','Salados'],['copa','De copa'],['bebida','Bebidas']].map(([id,n])=>button(n,'category','tab '+(state.category===id?'active':''),`data-id="${id}"`)).join('')}</div>`}
function menuModal(workMode=false){state.catalogWork=workMode;modal(`<div class="menu-header"><span class="eyebrow">${workMode?'ELEGÍ QUÉ VAS A PREPARAR':'ALGO RICO TE ESTÁ ESPERANDO'}</span><h2>${workMode?'Tu cocina, con cariño.':'El menú de Delfi'}</h2><p>${workMode?'Seguí la receta y revisá el frosting del ticket.':'La especialidad de la casa: rolls de canela. Hoy invita Delfi.'}</p></div>${tabs()}<div class="menu-grid">${MENU.filter(p=>p.category===state.category).map(p=>`<button class="menu-item" data-action="${workMode?'prepare':'add-cart'}" data-id="${p.id}">${food(p.id)}<div><strong>${p.name}</strong><p>${p.description}</p><span>${workMode?'Preparar →':`${p.price} ✦ · Agregar +`}</span></div></button>`).join('')}</div>${!workMode?`<div class="cart-bar"><div class="cart-summary">${state.cart.length?state.cart.map((p,i)=>`<button data-action="remove-cart" data-index="${i}" title="Quitar">${item(p.id).name}${p.frosting?' · '+FROSTINGS.find(f=>f.id===p.frosting).name:''} ×</button>`).join(''):'Elegí hasta 4 cosas ricas. La merienda es gratis.'}</div>${button(`Pedir ${state.cart.length?`(${state.cart.length})`:''} →`,'place-order','primary',state.cart.length?'':'disabled')}</div>`:''}`,'menu-modal')}
function frostingModal(id,mode){modal(`<span class="eyebrow">EL TOQUE FINAL</span><h2>¿Con qué frosting?</h2><p>${item(id).name}</p><div class="frosting-options">${FROSTINGS.map(f=>`<button class="frosting-option" data-action="${mode}" data-id="${id}" data-frosting="${f.id}">${food(id,f.id)}<strong>${f.name}</strong></button>`).join('')}</div>`)}
const names=['Lucía','Mateo','Sofía','Bruno','Valentina','Emma','Nico','Julieta'];
function createOrder(number){let items;if(number===1&&progress.served===0)items=[{id:'roll',frosting:'cream'},{id:'latte'}];else{const foods=MENU.filter(x=>x.category!=='bebida'),p=foods[Math.floor(Math.random()*foods.length)];items=[{id:p.id,...(p.art==='roll'?{frosting:FROSTINGS[Math.floor(Math.random()*3)].id}:{})}];if(number%2===1)items.push({id:MENU.filter(x=>x.category==='bebida')[Math.floor(Math.random()*5)].id})}const delivery=number%2===0?'takeaway':'here';return {number,name:names[(progress.served+number-1)%names.length],items,delivery,quote:delivery==='here'?'Hola, me quedo un ratito. ¡Qué rico huele!':'Me lo llevo para el camino, por favor. ¡Gracias!'}}
function startWork(){clearTimeout(pending);state={...state,scene:'work',orders:[createOrder(1)],tray:[],completed:0,earned:0,delivery:'here',prep:null};closeModal();render();if(progress.served===0)modal('<span class="eyebrow">TU PRIMER TURNO</span><h2>Vamos paso a paso ♡</h2><p>Lucía pidió un roll de canela con frosting de crema y un café con leche, para comer aquí.</p><ol class="help-list"><li>Abrí <b>Pastelería</b> y elegí el roll de canela.</li><li>Completá la receta. En el horno, frená la aguja en la zona verde.</li><li>Prepará el café en la <b>Barra de café</b>.</li><li>Elegí <b>Plato</b> y entregá el pedido.</li></ol><p>Podés equivocarte y volver a intentar. Nadie te apura.</p>'+button('¡Vamos, Delfi!','close'))}
function prepStart(id){if(state.tray.length>=4)return toast('La bandeja está llena. Retirá algún producto.');state.prep={id,step:0,frosting:null,quality:100,baking:false,baked:false};renderPrep()}
function prepChoices(step){if(step==='Frosting')return FROSTINGS.map(f=>({label:f.name,value:f.id,correct:true}));const wrong=step.includes('canela')?'Agregar sal y pimienta':step.includes('café')||step.includes('espresso')?'Agregar limonada':step==='Emplatar'?'Guardar sin terminar':step.includes('leche')?'Agregar salsa de tomate':step.includes('manzana')?'Agregar jamón':step.includes('chocolate')?'Agregar mostaza':step.includes('pan')?'Agregar helado':'Agregar un ingrediente distinto';return [{label:step,value:step,correct:true},{label:wrong,value:wrong,correct:false}].sort((a,b)=>a.label.localeCompare(b.label))}
function preparationArt(p){
 const m=item(p.id);
 if(m.art!=='roll'||p.step>=3)return food(p.id,p.frosting||(m.art==='roll'?'none':'cream'),true);
 const dough=p.step===0?'<ellipse cx="60" cy="69" rx="38" ry="28" fill="#ead0a1" stroke="#d8b57f" stroke-width="2"/><path d="M37 55q15-15 31-6" fill="none" stroke="#f8e4bd" stroke-width="5" stroke-linecap="round"/>':'<rect x="19" y="25" width="82" height="70" rx="9" fill="#ead0a1" stroke="#d8b57f" stroke-width="2"/>';
 const filling=p.step>=2?'<path d="M28 37h64m-64 12h64m-64 12h64m-64 12h64m-64 12h64" stroke="#a97142" stroke-width="7" stroke-linecap="round"/>'+ (p.id==='apple-roll'?'<path d="M33 42l9-5 5 8-9 5M67 65l9-5 5 8-9 5M48 77l9-5 5 8-9 5" fill="#e6b56e"/>':''):'';
 return `<svg class="food-art large" viewBox="0 0 120 120" role="img" aria-label="Masa en preparación"><ellipse cx="60" cy="102" rx="50" ry="8" fill="#614836" opacity=".1"/>${dough}${filling}</svg>`;
}
function renderPrep(){const p=state.prep;if(!p)return;const m=item(p.id),step=m.steps[p.step],heat=['Hornear','Tostar','Dejar infusionar'].includes(step);modal(`<div class="prep-heading"><span class="eyebrow">${m.category==='bebida'?'BARRA DE CAFÉ':'COCINA DE DELFI'}</span><h2>${m.name}</h2><div class="step-dots">${m.steps.map((s,i)=>`<span class="${i<p.step?'done':i===p.step?'current':''}" title="${s}">${i<p.step?'✓':i+1}</span>`).join('')}</div></div><div class="prep-body"><div class="prep-visual">${preparationArt(p)}<div class="ingredient-sparkle">✧</div><p>${p.step===0?'Todo listo para empezar':p.frosting?FROSTINGS.find(f=>f.id===p.frosting).name:'Va quedando precioso'}</p></div><div class="prep-instructions"><span class="eyebrow">PASO ${p.step+1} DE ${m.steps.length}</span><h3>${step}</h3><p>${step==='Frosting'?'Elegí el sabor que pidió el cliente.':heat?'Frená la aguja dentro de la zona verde. Si se pasa, podés volver a intentar.':'Elegí la acción de la receta para continuar.'}</p>${heat?`<div class="bake-gauge"><div class="sweet-zone"></div><div id="bake-needle"></div></div><div class="gauge-labels"><span>le falta</span><span>justo ♡</span><span>se pasa</span></div>${button('Empezar','start-bake','primary','id="bake-button"')}`:`<div class="prep-options">${prepChoices(step).map(c=>button(c.label,'prep-step','ingredient-button',`data-value="${esc(c.value)}" data-correct="${c.correct}"`)).join('')}</div>`}<small class="prep-hint">${step==='Frosting'?'Ticket: '+(FROSTINGS.find(f=>f.id===state.orders[0].items.find(x=>x.id===p.id)?.frosting)?.name||'este producto no figura en el pedido'):'Preparar también es una forma de cuidar.'}</small></div></div>`,'prep-modal')}
function nextStep(){const p=state.prep;if(!p)return;tone(650,.12);p.step++;if(p.step>=item(p.id).steps.length){state.tray.push({id:p.id,...(p.frosting?{frosting:p.frosting}:{}),quality:p.quality});state.prep=null;closeModal();render();toast('¡Listo! El producto está en tu bandeja.')}else renderPrep()}
function startBake(){const p=state.prep;if(!p)return;if(p.baking){const pos=p.position;p.baking=false;clearInterval(bakeTimer);if(pos>=40&&pos<=70){tone(880,.25);nextStep()}else{toast('Casi… Volvé a intentar: frená en la zona verde.');$('#bake-button').textContent='Intentar de nuevo';p.quality=Math.max(75,p.quality-5)}return}p.baking=true;p.started=performance.now();$('#bake-button').textContent='¡Sacar en el punto justo!';bakeTimer=setInterval(()=>{if(!state.prep)return clearInterval(bakeTimer);p.position=(1-Math.cos((performance.now()-p.started)/1100))/2*100;const needle=$('#bake-needle');if(needle)needle.style.left=p.position+'%'},25)}
function serve(){const o=state.orders[0],result=validateOrder(o.items,state.tray,o.delivery,state.delivery);if(!result.ok){tone(220,.2);toast(result.reason);return}let total=o.items.reduce((a,p)=>a+item(p.id).price,0),quality=state.tray.reduce((a,p)=>a+p.quality,0)/state.tray.length,tip=quality>=95?5:2;state.earned+=total+tip;progress.coins+=total+tip;progress.served++;state.completed++;state.tray=[];save();tone(784,.4);if(state.completed===5){progress.day++;progress.best=Math.max(progress.best,state.earned);save();state.scene='summary';render()}else{const name=o.name;state.orders=[createOrder(state.completed+1)];state.delivery='here';render();toast(`${name}: “¡Está riquísimo!” +${total} ✦ y ${tip} ✦ de propina.`)}}
function goHome(){clearTimeout(pending);closeModal();state.scene='welcome';state.seat=null;state.cart=[];render()}
function help(){modal('<span class="eyebrow">ESTÁS EN CASA</span><h2>Un café, a tu ritmo.</h2><div class="help-columns"><div><h3>Venir a merendar</h3><p>Elegí una mesa, abrí el menú y pedí hasta cuatro productos. Delfi te los trae. Hacé clic en cada uno para disfrutarlo. La visita es gratis.</p></div><div><h3>Trabajar con Delfi</h3><p>Leé el ticket, elegí una estación y seguí las recetas. Elegí el frosting correcto. Usá plato para comer aquí o caja para llevar. Atendé cinco pedidos para completar el turno.</p></div></div><p>Usá el mouse. <b>Escape</b> cierra ventanas; <b>1</b> y <b>2</b> eligen modo desde la entrada. ♫ activa la música. ⛶ amplía la pantalla.</p><p>Las monedas y los turnos completados se guardan en este navegador. Un pedido en preparación no se guarda.</p><div class="help-progress"><b>'+progress.served+'</b> pedidos atendidos · <b>'+progress.visits+'</b> meriendas compartidas</div>'+button('Volver al café','close'))}
function recipes(){modal(`<span class="eyebrow">EL CUADERNO DE DELFI</span><h2>Recetas para compartir.</h2><div class="recipe-list">${MENU.map(p=>`<details><summary>${p.name}</summary><ol>${p.steps.map(s=>`<li>${s}</li>`).join('')}</ol></details>`).join('')}</div>`)}
function finishMeal(){progress.visits++;save();state.scene='guest';state.meal=[];render();modal('<span class="eyebrow">DELFI</span><h2>Gracias por venir ♡</h2><p>Ojalá te lleves un poquito de la calma de este lugar. Acá siempre va a haber algo rico esperándote.</p>'+button('Pedir otra cosita','menu')+button('Volver a la entrada','home','secondary'))}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;tone(520,.06);switch(a){
case 'home':if(state.scene==='work'){modal('<h2>¿Terminamos el turno?</h2><p>Conservás las monedas de los pedidos entregados. Se descarta lo que estás preparando.</p>'+button('Sí, volver a la entrada','confirm-home')+button('Seguir trabajando','close','secondary'));}else goHome();break;
case 'confirm-home':goHome();break;
case 'sound':toggleSound();break;
case 'fullscreen':if(document.fullscreenElement)document.exitFullscreen?.();else document.documentElement.requestFullscreen?.().catch(()=>toast('Usá F11 para ampliar la ventana.'));break;
case 'help':help();break;
case 'close':closeModal();break;
case 'guest':clearTimeout(pending);closeModal();state.scene='guest';state.seat=null;state.cart=[];render();break;
case 'work':startWork();break;
case 'seat':state.seat=Number(b.dataset.id);render();break;
case 'menu':state.category='dulce';menuModal();break;
case 'category':state.category=b.dataset.id;menuModal(state.catalogWork);break;
case 'add-cart':if(state.cart.length>=4){toast('Con cuatro cositas alcanza para esta bandeja.');break}if(item(b.dataset.id).art==='roll')frostingModal(b.dataset.id,'cart-frosting');else{state.cart.push({id:b.dataset.id});menuModal()}break;
case 'cart-frosting':state.cart.push({id:b.dataset.id,frosting:b.dataset.frosting});menuModal();break;
case 'remove-cart':state.cart.splice(Number(b.dataset.index),1);menuModal();break;
case 'place-order':if(!state.cart.length)break;state.meal=[...state.cart];state.cart=[];state.scene='waiting';closeModal();render();pending=setTimeout(()=>{state.scene='meal';render();tone(784,.4)},2600);break;
case 'eat':state.meal.splice(Number(b.dataset.index),1);tone(784,.25);if(state.meal.length){render();toast('Un bocadito de felicidad. ♡')}else finishMeal();break;
case 'finish-meal':finishMeal();break;
case 'catalog':state.category=b.dataset.category;menuModal(true);break;
case 'prepare':prepStart(b.dataset.id);break;
case 'prep-step':if(!state.prep)break;if(b.dataset.correct!=='true'){toast('Mirá la receta: en este paso necesitamos otra cosa.');break}if(item(state.prep.id).steps[state.prep.step]==='Frosting')state.prep.frosting=b.dataset.value;nextStep();break;
case 'start-bake':startBake();break;
case 'remove-tray':state.tray.splice(Number(b.dataset.index),1);render();break;
case 'pack':state.delivery=b.dataset.id;render();break;
case 'serve':serve();break;
case 'recipes':recipes();break;
case 'leave-shift':modal('<h2>¿Nos tomamos una pausa?</h2><p>Las monedas ganadas quedan guardadas. El pedido actual se descarta.</p>'+button('Volver a la entrada','confirm-home')+button('Seguir con Delfi','close','secondary'));break;
case 'decor':if(progress.coins<60){toast('Necesitás 60 monedas. Podés ganarlas trabajando con Delfi.');break}progress.coins-=60;progress.decor=true;save();render();toast('Delfi: “¡Me encanta! La pongo en nuestro rincón favorito.”');break;
}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();return}if($('.modal')){if(e.key==='Tab'){const els=[...$('.modal').querySelectorAll('button:not([disabled]),summary,[tabindex="0"]')];if(!els.length)return;const first=els[0],last=els.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===$('.modal'))){last.focus();e.preventDefault()}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault()}}return}if(state.scene==='welcome'&&['1','2'].includes(e.key)){if(e.key==='1'){state.scene='guest';state.seat=null;render()}else startWork()}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&audio)audio.suspend();else if(state.sound&&audio)audio.resume()});
render();
