'use strict';
const {SHOP,CUSTOMERS,PETS}=CafeLiving;
CafeLiving.normalize(progress);
let sceneTimers=new Set(),sceneEpoch=0;
state.guestPhase='choosing';state.customerPhase='waiting';state.serving=false;state.consumed=[];state.visitRated=false;
const hasUpgrade=id=>progress.owned.includes(id);
function later(fn,ms){const epoch=sceneEpoch;const timer=setTimeout(()=>{sceneTimers.delete(timer);if(epoch===sceneEpoch)fn()},ms);sceneTimers.add(timer);return timer}
function clearScene(){sceneEpoch++;for(const t of sceneTimers)clearTimeout(t);sceneTimers.clear();clearTimeout(pending);state.serving=false;}
function sprite(index,cls='',name=''){return `<span class="actor-sprite ${cls}" style="--sx:${index%4};--sy:${Math.floor(index/4)}" role="img" aria-label="${esc(name)}"></span>`}
function ornaments(){return `${hasUpgrade('lights')?'<div class="fairy-lights" aria-label="Guirnalda comprada">'+Array.from({length:12},(_,i)=>`<i style="--i:${i}"></i>`).join('')+'</div>':''}${hasUpgrade('plant')?'<div class="bought-plant" title="La planta que le regalaste a Delfi"><svg width="85" height="115" viewBox="0 0 85 115" role="img" aria-label="Planta comprada"><path d="M42 82V27" stroke="#536745" stroke-width="4"/><path d="M42 61Q7 61 12 30q31 0 30 31m0-16Q43 8 67 12q9 27-25 33m0 25q7-34 35-27 0 30-35 27" fill="#80976a"/><path d="M17 78h53l-8 32H26Z" fill="#b77957"/><path d="M13 75h60v10H13Z" fill="#d79e71"/></svg></div>':''}`}
function petsDock(){return `<div class="pet-dock ${hasUpgrade('pet-beds')?'with-beds':''}"><span class="pet-dock-label">UN RATITO CON ELLOS ♡</span><div>${PETS.map(p=>`<button class="pet-hit" data-action="pet" data-id="${p.id}" aria-label="Acariciar a ${p.name}">${sprite(p.sprite,'pet-idle',p.name)}<small>${p.name}</small></button>`).join('')}</div></div>`}
const originalHeader=header;
header=function(){return originalHeader().replace(/<span class="coin"[^>]*>.*?<\/span>/,button(`${progress.coins} ✦ <span>Tienda</span>`,'shop','coin shop-trigger','title="Gastar tus estrellas"'))};
const originalWelcome=welcome;
welcome=function(){return originalWelcome().replace('<div class="scene-caption">',petsDock()+'<div class="scene-caption">')};
function delfiActor(){const p=state.guestPhase,index=p==='leaving'?1:p==='returning'||p==='served'||p==='tasting'?2:0;return `<div class="delfi-actor phase-${p}">${sprite(index,'delfi-breathe','Delfi')}<div class="actor-bubble">${({arriving:'¡Ya voy con vos!',taking:'¿Qué te gustaría pedir?',leaving:'Lo anoto y ya vuelvo ♡',preparing:'',returning:'¡Acá viene algo rico!',served:'¡Que lo disfrutes!',tasting:'¿Qué te pareció?'}[p]||'')}</div></div>`}
guest=function(){const seated=state.seat!==null,p=state.guestPhase,meal=state.scene==='meal',waiting=state.scene==='waiting';const lines={arriving:'¡Qué lindo lugar elegiste! Ya me acerco a tomar tu pedido.',taking:'Te escucho. ¿Un roll con frosting o algo de nuestra nueva carta de bebidas?',leaving:'Perfecto, lo anoté. Voy a prepararlo con cariño.',preparing:'Delfi está preparando tu pedido en el mostrador. Podés acariciar a las mascotas mientras esperás.',returning:'¡Acá estoy! Recién preparado y servido con cariño.',served:'Probá lo que pediste. Después me encantaría saber qué te pareció.',tasting:'Tomate tu tiempo. ¿Qué tal está?'};return `<main class="scene lounge living-room ${seated?'seat-view seat-'+state.seat:''} ${hasUpgrade('lavender')?'lavender-room':''}"><div class="scene-image interior ${seated?'camera-'+state.seat:''}"></div><div class="room-vignette"></div>${ornaments()}<div class="scene-label"><span class="eyebrow">${seated?'TU MESA · '+(waiting?'EN PREPARACIÓN':'DISFRUTÁ EL MOMENTO'):'EL SALÓN'}</span><h2>${seated?seats[state.seat].name:'Elegí tu lugar favorito'}</h2>${seated?button('← Cambiar de mesa','change-seat','seat-return',waiting||meal?'disabled':''):''}</div>${seated?delfiActor():seats.map(s=>`<button class="seat-hotspot" style="left:${s.x}%;top:${s.y}%" data-action="seat" data-id="${s.id}"><span>＋</span>${s.name}</button>`).join('')}${p==='preparing'?'<div class="preparing-note"><span class="steam">♨</span><p>Se siente el aroma desde la cocina…</p><small>Delfi vuelve enseguida.</small></div>':''}${meal?`<div class="table-service animated-service"><span class="eyebrow">PROBÁ TU PEDIDO · DESPUÉS PODÉS VALORARLO</span><div class="served-food">${state.meal.map((a,i)=>`<button data-action="eat" data-index="${i}" class="served-item">${food(a.id,a.frosting,true)}<span>${item(a.id).name}</span></button>`).join('')}</div></div>`:''}${petsDock()}</main>${dialogue('DELFI',seated?lines[p]||lines.taking:'Elegí una mesa. Yo me acerco a acompañarte y a anotar lo que te guste.',!seated?button('Volver','home','text-button'):p==='taking'?button('Delfi, quiero pedir →','menu'):meal?button('Terminar y valorar ☆','finish-meal','secondary'):'')}`};
function selectSeat(id){clearScene();state.scene='guest';state.seat=id;state.guestPhase='arriving';state.consumed=[];state.visitRated=false;state.cart=[];render();later(()=>{state.guestPhase='taking';render()},1400)}
function startVisit(){clearScene();closeModal();state.scene='guest';state.seat=null;state.cart=[];state.guestPhase='choosing';render()}
function placeOrder(){if(!state.cart.length||state.scene!=='guest')return;state.meal=state.cart.map(p=>({...p}));state.orderHistory=state.meal.map(p=>({...p}));state.cart=[];state.scene='waiting';state.guestPhase='leaving';closeModal();render();later(()=>{state.guestPhase='preparing';render()},1300);later(()=>{state.guestPhase='returning';render()},4900);later(()=>{state.scene='meal';state.guestPhase='served';render();tone(784,.4)},6500)}
finishMeal=function(){if(state.visitRated)return;state.scene='guest';state.guestPhase='taking';state.meal=[];render();modal(`<span class="eyebrow">DELFI QUIERE SABER</span><h2>¿Cómo estuvo tu merienda?</h2><p>${state.consumed.length?'Probaste '+state.consumed.length+' producto(s).':'Gracias por compartir este ratito.'} Tu valoración queda en el cuaderno del café.</p><div class="rating-stars" role="group" aria-label="Valorar de una a cinco estrellas">${[1,2,3,4,5].map(n=>button('★'.repeat(n),'rate','rating-choice',`data-id="${n}" aria-label="${n} estrellas"`)).join('')}</div><p class="rating-note">Tu opinión no gasta ni entrega estrellas de la tienda.</p>`)};
function rateVisit(n){if(state.visitRated)return;state.visitRated=true;progress.visits++;progress.ratings.push({stars:n,seat:seats[state.seat].name,items:(state.orderHistory||[]).map(p=>p.id),at:Date.now()});progress.ratings=progress.ratings.slice(-20);save();modal(`<span class="eyebrow">${'★'.repeat(n)}</span><h2>${n>=4?'¡Me alegra que te haya gustado!':'Gracias por decírmelo con sinceridad.'}</h2><p>${n>=4?'Delfi sonríe: “Acá siempre tenés una mesa esperándote.”':'Delfi anota tu opinión: “Voy a seguir mejorando, gracias por venir.”'}</p>${button('Pedir otra cosita','another-order')}${button('Volver a la entrada','home','secondary')}`)}
createOrder=function(number){let products;if(number===1&&progress.served===0)products=[{id:'roll',frosting:'cream'},{id:'latte'}];else{const foods=MENU.filter(p=>p.category!=='bebida'),drinks=MENU.filter(p=>p.category==='bebida');const p=foods[Math.floor(Math.random()*foods.length)];products=[{id:p.id,...(p.art==='roll'?{frosting:FROSTINGS[Math.floor(Math.random()*3)].id}:{})}];const d=drinks[Math.floor(Math.random()*drinks.length)];products.push({id:d.id})}const c=CUSTOMERS[(number-1+(Math.max(1,progress.day)-1)*5)%5],delivery=number%2===0?'takeaway':'here';return {number,name:c.name,customerId:c.id,sprite:c.sprite,items:products,delivery,quote:c.quote+(delivery==='takeaway'?' Para llevar, por favor.':' Me quedo a comer aquí.')}};
const originalWork=work;
work=function(){const o=state.orders[0];let html=originalWork();html=html.replace('<div class="station-grid">',`<div class="customer-stage"><div class="customer-person ${state.customerPhase}">${sprite(o.sprite||4,'customer-idle',o.name)}</div><div class="customer-message"><span class="eyebrow">${state.customerPhase==='leaving'?'GRACIAS POR VENIR':'EN EL MOSTRADOR'}</span><h3>${o.name}</h3><p>${state.customerPhase==='leaving'?'¡Riquísimo! Nos vemos pronto. ♡':o.quote}</p>${state.customerPhase==='leaving'?`<strong>+${state.lastEarning||0} ✦ · ${'★'.repeat(state.lastRating||5)}</strong>`:''}</div><div class="counter-edge"></div></div><div class="station-grid">`);html=html.replace('<div class="kitchen-backdrop"></div>','<div class="kitchen-backdrop"></div>'+ornaments());html=html.replace('data-category="bebida"','data-category="hot"');html=html.replace('monedas','estrellas');html=html.replace('data-action="serve"','data-action="serve" '+(state.serving?'disabled':''));return html};
const originalStartWork=startWork;
startWork=function(){clearScene();state.customerPhase='entering';originalStartWork();later(()=>{if(state.scene==='work'){state.customerPhase='waiting';render()}},1400)};
serve=function(){if(state.serving||state.scene!=='work')return;const o=state.orders[0],r=validateOrder(o.items,state.tray,o.delivery,state.delivery);if(!r.ok){toast(r.reason);tone(220,.2);return}const total=o.items.reduce((sum,p)=>sum+item(p.id).price,0),quality=state.tray.reduce((s,p)=>s+p.quality,0)/state.tray.length;const tip=quality>=95?5:2;state.lastRating=quality>=95?5:4;state.lastEarning=total+tip;state.earned+=total+tip;progress.coins+=total+tip;progress.served++;state.completed++;state.tray=[];state.serving=true;state.customerPhase='leaving';save();render();tone(784,.4);later(()=>{state.serving=false;if(state.completed===5){progress.day++;progress.best=Math.max(progress.best,state.earned);save();state.scene='summary';render()}else{state.orders=[createOrder(state.completed+1)];state.delivery='here';state.customerPhase='entering';render();later(()=>{if(state.scene==='work'){state.customerPhase='waiting';render()}},1400)}},2000)};
const originalSummary=summary;
summary=function(){return originalSummary().replace('monedas ganadas','estrellas ganadas').replace('Regalar una planta · 60 ✦','Abrir tienda de estrellas ✦').replace('data-action="decor"','data-action="shop"')};
const originalHome=goHome;
goHome=function(){clearScene();state.guestPhase='choosing';originalHome()};
tabs=function(){return `<div class="tabs" role="group" aria-label="Categoría">${[['dulce','Dulces'],['salado','Salados'],['copa','De copa'],['hot','Calientes'],['cold','Frías']].map(([id,n])=>button(n,'category','tab '+(state.category===id?'active':''),`data-id="${id}"`)).join('')}</div>`};
function menuFilter(p){return state.category==='hot'||state.category==='cold'?p.category==='bebida'&&p.temperature===state.category:p.category===state.category}
menuModal=function(workMode=false){if(!workMode&&state.scene==='guest'&&state.seat!==null&&state.guestPhase==='arriving')return;state.catalogWork=workMode;const arr=MENU.filter(menuFilter);modal(`<div class="menu-header"><span class="eyebrow">${workMode?'EN LA COCINA':'DELFI ESTÁ ANOTANDO TU PEDIDO'}</span><h2>${workMode?'¿Qué preparamos?':'Nuestra carta, con cariño.'}</h2><p>${workMode?'Revisá el ticket y elegí el producto correcto.':'Elegí hasta cuatro productos. La merienda es gratis.'}</p></div>${tabs()}<input class="menu-search" type="search" placeholder="Buscar en esta sección…" aria-label="Buscar un producto"><div class="menu-grid">${arr.map(p=>`<button class="menu-item" data-search="${esc(p.name.toLowerCase())}" data-action="${workMode?'prepare':'add-cart'}" data-id="${p.id}">${food(p.id)}<div><strong>${p.name}</strong><p>${p.description}</p><span>${workMode?'Preparar →':p.price+' ✦ · Agregar +'}</span></div></button>`).join('')}</div><p class="no-results" hidden>No encontré ese producto en esta sección.</p>${!workMode?`<div class="cart-bar"><div class="cart-summary">${state.cart.length?state.cart.map((p,i)=>`<button data-action="remove-cart" data-index="${i}">${item(p.id).name}${p.frosting?' · '+FROSTINGS.find(f=>f.id===p.frosting).name:''} ×</button>`).join(''):'Delfi te recomienda un roll de canela.'}</div>${button('Anotar pedido ('+state.cart.length+') →','place-order','primary',state.cart.length?'':'disabled')}</div>`:''}`,'menu-modal')};
function shop(){modal(`<span class="eyebrow">CADA PEDIDO HACE CRECER ESTE LUGAR</span><h2>Pequeñas cosas, mucha alegría.</h2><p class="shop-balance">Tenés <strong>${progress.coins} ✦</strong> estrellas para gastar.</p><div class="shop-grid">${SHOP.map(u=>`<article class="shop-card"><div class="shop-art">${u.icon}</div><h3>${u.name}</h3><p>${u.description}</p>${button(hasUpgrade(u.id)?'Comprado ✓':u.price+' ✦ · Comprar','buy-upgrade',hasUpgrade(u.id)?'secondary':'primary',`data-id="${u.id}" ${hasUpgrade(u.id)?'disabled':''}`)}</article>`).join('')}</div><p class="shop-footnote">Se conservan las estrellas de tu versión anterior. Las mejoras se guardan en este navegador.</p>`,'shop-modal')}
function petModal(id,reaction=false){const p=PETS.find(p=>p.id===id);if(!p)return;modal(`<span class="eyebrow">LOS COMPAÑEROS DE DELFI</span><h2>${p.name}</h2><div class="pet-closeup ${reaction?'pet-reacting':''}">${sprite(p.sprite,'',p.name)}${reaction?'<div class="heart-burst"><i>♡</i><i>♡</i><i>♡</i></div>':''}${hasUpgrade('pet-beds')?'<div class="pet-cushion"></div>':''}</div><p class="pet-message">${reaction?p.line:'Acercate despacito. Le encantan las caricias.'}</p><div class="affection">♡ ${progress.affection[id]||0} momentos compartidos</div><div class="pet-actions">${button('Acariciar ♡','pet-stroke','primary',`data-id="${id}"`)}${hasUpgrade('treats')?button('Dar un premio','pet-treat','secondary',`data-id="${id}"`):button('Premios en la tienda · 40 ✦','shop','text-button')}</div>`,'pet-modal')}
function stroke(id,treat=false){const p=PETS.find(p=>p.id===id);if(!p||treat&&!hasUpgrade('treats'))return;progress.affection[id]=Math.max(0,Number(progress.affection[id])||0)+(treat?2:1);save();petModal(id,true);tone(id==='canelita'?440:130,.45,.03)}
const originalHelp=help;
help=function(){originalHelp();$('.modal').insertAdjacentHTML('beforeend','<h3>Ahora hay más vida en el café</h3><p>Elegí una mesa para acercarte. Delfi toma tu pedido, va a la cocina y vuelve. Probá los productos y valorá tu visita. Tocá a Miguel, Phoebe o Canelita para acariciarlos. En el trabajo llegan cinco clientes diferentes. Abrí la tienda con el botón de estrellas de arriba.</p>')};
// The upgraded oven preserves the same minigame, with a wider success window.
startBake=function(){const p=state.prep;if(!p)return;const min=hasUpgrade('oven')?30:40,max=hasUpgrade('oven')?80:70;if(p.baking){const pos=p.position;p.baking=false;clearInterval(bakeTimer);if(pos>=min&&pos<=max){tone(880,.25);nextStep()}else{toast('Casi… frená la aguja en la zona verde.');$('#bake-button').textContent='Intentar de nuevo';p.quality=Math.max(75,p.quality-5)}return}p.baking=true;p.started=performance.now();const zone=$('.sweet-zone');zone.style.left=min+'%';zone.style.width=(max-min)+'%';$('#bake-button').textContent='¡Sacar en el punto justo!';bakeTimer=setInterval(()=>{if(!state.prep)return clearInterval(bakeTimer);p.position=(1-Math.cos((performance.now()-p.started)/1100))/2*100;const needle=$('#bake-needle');if(needle)needle.style.left=p.position+'%'},25)};
const originalRenderPrep=renderPrep;
renderPrep=function(){originalRenderPrep();if(hasUpgrade('oven')&&$('.sweet-zone')){$('.sweet-zone').style.left='30%';$('.sweet-zone').style.width='50%'}};
document.addEventListener('input',e=>{if(!e.target.matches('.menu-search'))return;const q=e.target.value.toLocaleLowerCase();let count=0;document.querySelectorAll('.menu-item').forEach(el=>{el.hidden=!el.dataset.search.includes(q);if(!el.hidden)count++});$('.no-results').hidden=count>0});
// Capture only the extended actions; ordinary cooking controls keep using game.js.
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;if(!['guest','seat','change-seat','place-order','eat','shop','buy-upgrade','pet','pet-stroke','pet-treat','rate','another-order'].includes(a))return;e.preventDefault();e.stopImmediatePropagation();tone(520,.06);switch(a){
case 'guest':startVisit();break;
case 'seat':selectSeat(Number(b.dataset.id));break;
case 'change-seat':startVisit();break;
case 'place-order':placeOrder();break;
case 'eat':{if(state.scene!=='meal')break;const i=Number(b.dataset.index),p=state.meal[i];if(!p)break;state.consumed.push(p);state.meal.splice(i,1);state.guestPhase='tasting';tone(784,.25);if(state.meal.length){render();toast('Un bocadito de felicidad. ♡')}else finishMeal();break}
case 'shop':shop();break;
case 'buy-upgrade':{const r=CafeLiving.buy(progress,b.dataset.id);if(r.ok){save();render();shop();toast('Delfi: “¡Qué lindo! '+r.item.name+' ya está en el café.”')}else toast(r.reason);break}
case 'pet':stroke(b.dataset.id);break;
case 'pet-stroke':stroke(b.dataset.id);break;
case 'pet-treat':stroke(b.dataset.id,true);break;
case 'rate':rateVisit(Number(b.dataset.id));break;
case 'another-order':state.visitRated=false;state.consumed=[];state.guestPhase='taking';closeModal();menuModal();break;
}},true);
// Patch ingredient illustrations for the expanded cold drinks without external images.
const originalFood=food;
food=function(id,frosting='cream',large=false){const p=item(id);if(!p||!['shake','smoothie','juice','iced'].includes(p.art))return originalFood(id,frosting,large);const color=id.includes('chocolate')||id.includes('mocha')?'#956347':id.includes('strawberry')||id.includes('berries')||id.includes('raspberry')?'#d797a0':id.includes('lavender')?'#b8aad0':id.includes('orange')||id.includes('mango')?'#efb365':p.art==='iced'||id.includes('espresso')?'#b58b69':'#e5cd8e';return `<svg class="food-art ${large?'large':''}" viewBox="0 0 120 120" role="img" aria-label="${esc(p.name)}"><ellipse cx="60" cy="104" rx="35" ry="8" fill="#68523d" opacity=".1"/><path d="M30 35h60l-8 65H38Z" fill="${color}" stroke="#e5d9c4" stroke-width="3"/><path d="M36 42h48l-2 10H38Z" fill="#fff" opacity=".25"/><path d="M68 55 86 9" stroke="#ae8a92" stroke-width="5"/>${p.art==='shake'?'<path d="M28 36q2-12 15-12-2-11 10-15 15 0 16 13 20-2 23 14Z" fill="#fff2d8"/>':'<rect x="44" y="48" width="12" height="12" rx="3" fill="#fff" opacity=".4"/><rect x="64" y="55" width="12" height="12" rx="3" fill="#fff" opacity=".4"/>'}</svg>`};
save();render();
