/* Data-driven menu. Prices are fictional game coins, not real currency. */
(function(root){
const steps=(...values)=>values;
const MENU=[
['roll','Roll de canela','dulce',8,'roll','Nuestro abrazo recién horneado.',steps('Estirar la masa','Agregar canela','Enrollar','Hornear','Frosting','Emplatar')],
['apple-roll','Roll de canela y manzana','dulce',10,'roll','Manzana tibia, canela y un poquito de magia.',steps('Estirar la masa','Agregar manzana y canela','Enrollar','Hornear','Frosting','Emplatar')],
['carrot','Carrot cake','dulce',9,'cake','Especias suaves y crema.',steps('Cortar una porción','Agregar crema','Decorar con nueces','Emplatar')],
['crumble','Crumble de manzana','dulce',8,'crumble','Manzana horneada bajo una capa crocante.',steps('Agregar manzana','Cubrir con crumble','Hornear','Emplatar')],
['berry-crumble','Crumble de manzana y frutos rojos','dulce',10,'crumble','Frutas dulces, ácidas y crumble dorado.',steps('Agregar manzana y frutos rojos','Cubrir con crumble','Hornear','Emplatar')],
['cat-cookie','Cookies de gatitos','dulce',6,'cat','Tan tiernas que da pena comerlas.',steps('Estirar la masa','Cortar gatitos','Hornear','Decorar caritas','Emplatar')],
['lemon-loaf','Budín de limón','dulce',7,'cake','Una rodaja de sol con glaseado.',steps('Cortar una porción','Agregar glaseado de limón','Emplatar')],
['brownie','Brownie','dulce',8,'brownie','Chocolate intenso y centro suave.',steps('Cortar un cuadrado','Agregar chocolate','Emplatar')],
['chocoflan','Chocoflan','copa',10,'flan','Dos capas, una cucharada feliz.',steps('Desmoldar','Agregar caramelo','Emplatar')],
['choco-mousse','Mousse de chocolate','copa',8,'mousse','Chocolate ligero como una nube.',steps('Llenar la copa de chocolate','Agregar crema','Decorar con chocolate','Emplatar')],
['lemon-mousse','Mousse de limón','copa',8,'mousse','Fresquita, cremosa y delicada.',steps('Llenar la copa de limón','Agregar crema','Decorar con limón','Emplatar')],
['cheesecake','Cheesecake de frutos rojos','copa',11,'cake','Crema suave con frutos del bosque.',steps('Cortar una porción','Agregar frutos rojos','Emplatar')],
['marble','Torta marmolada','dulce',7,'cake','Vainilla y chocolate, como en casa.',steps('Cortar una porción','Agregar chocolate','Emplatar')],
['danish','Galletitas danesas','dulce',6,'cookies','Manteca, vainilla y bordes doraditos.',steps('Formar las galletitas','Hornear','Espolvorear azúcar','Emplatar')],
['ferrero','Alfajor ferrero','dulce',9,'alfajor','Chocolate y avellanas crujientes.',steps('Unir las tapas con crema de avellanas','Bañar en chocolate','Agregar avellanas','Emplatar')],
['cheese-scone','Scones de queso','salado',8,'scone','Dorados por fuera, tiernos por dentro.',steps('Mezclar masa y queso','Cortar los scones','Hornear','Emplatar')],
['lomito','Sándwich de lomito, queso crema y rúcula','salado',12,'sandwich','Lomito, crema suave y hojas frescas.',steps('Cortar el pan','Untar queso crema','Agregar lomito','Agregar rúcula','Emplatar')],
['caprese','Sándwich capresse','salado',10,'sandwich','Muzzarella fresca, tomate y albahaca.',steps('Cortar el pan','Agregar tomate y muzzarella','Agregar albahaca','Emplatar')],
['avocado','Tostón de palta, huevo y verdes','salado',11,'sandwich','Crocante, cremoso y lleno de frescura.',steps('Colocar pan','Tostar','Agregar palta','Agregar huevo','Agregar verdes','Emplatar')],
['italian','Sándwich italiano','salado',14,'sandwich','Ciabatta, muzzarella, pesto, lomito, tomate y rúcula.',steps('Abrir pan ciabatta','Untar pesto','Agregar muzzarella fresca y lomito','Agregar tomate y rúcula','Terminar con aceite de oliva','Emplatar')],
['spinach-scone','Scones de espinaca y queso','salado',9,'scone','Queso y espinaca en una masa tierna.',steps('Mezclar masa, espinaca y queso','Cortar los scones','Hornear','Emplatar')],
['cheeseboard','Tabla de quesos','salado',18,'board','Suaves, azules y de cabra, con frutas y crocantes.',steps('Disponer quesos suaves, azules y de cabra','Agregar uvas, peras e higos','Agregar frutos secos','Agregar mermelada','Emplatar')],
['yogurt','Yogurt con granola y frutos rojos','copa',8,'mousse','Cremoso, crocante y fresco.',steps('Llenar la copa de yogurt','Agregar granola','Agregar frutos rojos','Emplatar')],
['fruit-tart','Tarta frutal','copa',10,'cake','Base de galletas, crema pastelera y frutas.',steps('Preparar base de galletas','Agregar crema pastelera','Decorar con frutas variadas','Emplatar')],
['fruit-salad','Ensalada de frutas','copa',7,'fruit','Frutas frescas de todos los colores.',steps('Cortar frutas variadas','Mezclar las frutas','Servir en copa','Emplatar')],
['icecream','Helado','copa',7,'icecream','Tres bochitas de pura felicidad.',steps('Preparar la copa','Agregar bochitas de helado','Agregar barquillo','Emplatar')],
['tiramisu','Tiramisú','copa',11,'mousse','Café, crema y una lluvia de cacao.',steps('Humedecer bizcochos con café','Agregar crema de mascarpone','Formar las capas','Espolvorear cacao','Emplatar')],
["espresso", "Expresso", "bebida", 4, "coffee", "Corto, intenso y aromático.", ["Moler café", "Extraer espresso", "Servir en taza"]],
["espresso-double", "Expresso doble", "bebida", 6, "coffee", "Un café preparado con cariño.", ["Moler café", "Extraer espresso", "Extraer una segunda medida", "Servir en taza"]],
["espresso-panna", "Expresso Panna", "bebida", 6, "coffee", "Un café preparado con cariño.", ["Moler café", "Extraer espresso", "Agregar crema batida", "Servir en taza"]],
["americano", "Americano", "bebida", 5, "coffee", "Un café preparado con cariño.", ["Moler café", "Extraer espresso", "Agregar agua caliente", "Servir en taza"]],
["latte", "Latte", "bebida", 5, "coffee", "Café con leche y un corazón de espuma.", ["Moler café", "Extraer espresso", "Vaporizar leche", "Dibujar un corazón", "Servir en taza"]],
["cortado", "Cortado", "bebida", 5, "coffee", "Un café preparado con cariño.", ["Moler café", "Extraer espresso", "Agregar un toque de leche", "Servir en taza"]],
["cappuccino", "Capuchino clásico", "bebida", 6, "coffee", "Un café preparado con cariño.", ["Moler café", "Extraer espresso", "Vaporizar leche", "Agregar espuma de leche", "Servir en taza"]],
["cappuccino-vanilla", "Capuchino de vainilla", "bebida", 7, "coffee", "Un café preparado con cariño.", ["Moler café", "Extraer espresso", "Agregar vainilla", "Vaporizar leche", "Agregar espuma de leche", "Servir en taza"]],
["frappe", "Frappé", "bebida", 8, "coffee", "Café batido, suave y cremoso.", ["Moler café", "Extraer espresso", "Agregar leche y hielo", "Licuar", "Agregar crema batida", "Servir en taza"]],
["mocha", "Mocha", "bebida", 7, "coffee", "Un café preparado con cariño.", ["Moler café", "Extraer espresso", "Agregar chocolate", "Vaporizar leche", "Servir en taza"]],
["dalgona", "Dalgona", "bebida", 8, "coffee", "Leche con una nube de café batido.", ["Mezclar café, azúcar y agua", "Batir hasta formar espuma", "Agregar leche", "Colocar la espuma de café", "Servir en taza"]],
["breve", "Breve", "bebida", 7, "coffee", "Un café preparado con cariño.", ["Moler café", "Extraer espresso", "Mezclar leche y crema", "Vaporizar la mezcla", "Servir en taza"]],
["hawaiian", "Hawaiano", "bebida", 8, "coffee", "Un café preparado con cariño.", ["Moler café", "Extraer espresso", "Agregar leche de coco", "Decorar con coco", "Servir en taza"]],
["affogato", "Affogato", "bebida", 8, "coffee", "Un café preparado con cariño.", ["Moler café", "Extraer espresso", "Colocar helado de vainilla", "Verter el espresso sobre el helado", "Servir en taza"]],
["caramel-latte", "Caramel latte", "bebida", 7, "coffee", "Un café preparado con cariño.", ["Moler café", "Extraer espresso", "Agregar caramelo", "Vaporizar leche", "Servir en taza"]],
["vanilla-latte", "Vainilla Latte", "bebida", 7, "coffee", "Un café preparado con cariño.", ["Moler café", "Extraer espresso", "Agregar vainilla", "Vaporizar leche", "Servir en taza"]],
["caramel-macchiato", "Caramel Macchiato", "bebida", 8, "coffee", "Un café preparado con cariño.", ["Moler café", "Extraer espresso", "Vaporizar leche", "Agregar caramelo en espiral", "Servir en taza"]],
["matcha", "Matcha Latte", "bebida", 7, "tea", "Matcha y leche suave.", ["Tamizar matcha", "Batir con agua caliente", "Agregar leche vaporizada", "Servir en taza"]],
["submarino", "Submarino", "bebida", 7, "coffee", "Una barrita de chocolate se sumerge en leche.", ["Calentar leche", "Colocar chocolate en la taza", "Verter leche caliente", "Servir en taza"]],
["chocolate", "Chocolate caliente", "bebida", 6, "coffee", "Chocolate cremoso para tardes lentas.", ["Agregar chocolate", "Verter leche caliente", "Mezclar", "Servir en taza"]],
["tea", "Té de lavanda", "bebida", 4, "tea", "Una pausa aromática.", ["Agregar té de lavanda", "Verter agua caliente", "Dejar infusionar", "Servir en taza"]],
["tea-black", "Té de negro", "bebida", 4, "tea", "Una pausa aromática.", ["Agregar té de negro", "Verter agua caliente", "Dejar infusionar", "Servir en taza"]],
["tea-green", "Té de verde", "bebida", 4, "tea", "Una pausa aromática.", ["Agregar té de verde", "Verter agua caliente", "Dejar infusionar", "Servir en taza"]],
["tea-chamomile", "Té de manzanilla", "bebida", 4, "tea", "Una pausa aromática.", ["Agregar té de manzanilla", "Verter agua caliente", "Dejar infusionar", "Servir en taza"]],
["milkshake-vanilla", "Milkshake de vainilla", "bebida", 8, "shake", "Helado, leche y tu sabor favorito.", ["Agregar helado de vainilla", "Agregar leche", "Licuar", "Agregar crema batida", "Servir en vaso"]],
["milkshake-strawberry", "Milkshake de frutilla", "bebida", 8, "shake", "Helado, leche y tu sabor favorito.", ["Agregar helado de frutilla", "Agregar leche", "Licuar", "Agregar crema batida", "Servir en vaso"]],
["milkshake-chocolate", "Milkshake de chocolate", "bebida", 8, "shake", "Helado, leche y tu sabor favorito.", ["Agregar helado de chocolate", "Agregar leche", "Licuar", "Agregar crema batida", "Servir en vaso"]],
["milkshake-espresso", "Milkshake de expresso", "bebida", 8, "shake", "Helado, leche y tu sabor favorito.", ["Agregar helado de expresso", "Agregar leche", "Licuar", "Agregar crema batida", "Servir en vaso"]],
["milkshake-mocha", "Milkshake de mocha", "bebida", 8, "shake", "Helado, leche y tu sabor favorito.", ["Agregar helado de mocha", "Agregar leche", "Licuar", "Agregar crema batida", "Servir en vaso"]],
["smoothie-banana", "Licuado de banana", "bebida", 7, "smoothie", "Fruta fresca y leche.", ["Cortar banana", "Agregar leche", "Licuar", "Servir en vaso"]],
["smoothie-strawberry", "Licuado de frutilla", "bebida", 7, "smoothie", "Fruta fresca y leche.", ["Cortar frutilla", "Agregar leche", "Licuar", "Servir en vaso"]],
["smoothie-mango", "Licuado de mango", "bebida", 7, "smoothie", "Fruta fresca y leche.", ["Cortar mango", "Agregar leche", "Licuar", "Servir en vaso"]],
["orange", "Jugo de naranja", "bebida", 6, "juice", "Naranjas exprimidas al momento.", ["Cortar naranjas", "Exprimir naranjas", "Colar el jugo", "Servir en vaso"]],
["lemonade", "Limonada", "bebida", 6, "lemonade", "Cítricos, frescura y hielo.", ["Preparar limón", "Agregar agua y azúcar", "Agregar hielo", "Servir en vaso"]],
["lemonade-berries", "Limonada de frutos rojos", "bebida", 6, "lemonade", "Cítricos, frescura y hielo.", ["Preparar limón y frutos rojos", "Agregar agua y azúcar", "Agregar hielo", "Servir en vaso"]],
["lemonade-raspberry", "Limonada de frambuesa", "bebida", 6, "lemonade", "Cítricos, frescura y hielo.", ["Preparar limón y frambuesa", "Agregar agua y azúcar", "Agregar hielo", "Servir en vaso"]],
["lemonade-lavender", "Limonada de lavanda", "bebida", 6, "lemonade", "Cítricos, frescura y hielo.", ["Preparar limón y lavanda", "Agregar agua y azúcar", "Agregar hielo", "Servir en vaso"]],
["grapefruit", "Pomelada", "bebida", 6, "lemonade", "Cítricos, frescura y hielo.", ["Preparar pomelo", "Agregar agua y azúcar", "Agregar hielo", "Servir en vaso"]],
["coffee-orange", "Coffee orange", "bebida", 8, "juice", "Naranja y café en capas.", ["Exprimir naranja", "Agregar hielo", "Extraer espresso", "Verter café sobre la naranja", "Servir en vaso"]],
["iced-tea-lemon", "Iced tea de limón", "bebida", 6, "juice", "Té frío con limón.", ["Preparar té frío", "Agregar limón", "Agregar hielo", "Servir en vaso"]],
["iced-tea-peach", "Iced tea de durazno", "bebida", 6, "juice", "Té frío con durazno.", ["Preparar té frío", "Agregar durazno", "Agregar hielo", "Servir en vaso"]],
["iced-tea-berries", "Iced tea de frutos rojos", "bebida", 6, "juice", "Té frío con frutos rojos.", ["Preparar té frío", "Agregar frutos rojos", "Agregar hielo", "Servir en vaso"]],
["iced-coffee-classic", "Iced coffee clásico", "bebida", 7, "iced", "Café fresco para una tarde soleada.", ["Extraer espresso", "Agregar leche fría", "Agregar sabor clásico", "Agregar hielo", "Servir en vaso"]],
["iced-coffee-vanilla", "Iced coffee vainilla", "bebida", 7, "iced", "Café fresco para una tarde soleada.", ["Extraer espresso", "Agregar leche fría", "Agregar sabor vainilla", "Agregar hielo", "Servir en vaso"]],
["iced-coffee-caramel", "Iced coffee caramelo", "bebida", 7, "iced", "Café fresco para una tarde soleada.", ["Extraer espresso", "Agregar leche fría", "Agregar sabor caramelo", "Agregar hielo", "Servir en vaso"]],
["soda-lemon", "Soda de limón", "bebida", 5, "juice", "Burbujas con limón.", ["Preparar sabor de limón", "Agregar agua con gas", "Agregar hielo", "Servir en vaso"]],
["soda-berries", "Soda de frutos rojos", "bebida", 5, "juice", "Burbujas con frutos rojos.", ["Preparar sabor de frutos rojos", "Agregar agua con gas", "Agregar hielo", "Servir en vaso"]],
["soda-lavender", "Soda de lavanda", "bebida", 5, "juice", "Burbujas con lavanda.", ["Preparar sabor de lavanda", "Agregar agua con gas", "Agregar hielo", "Servir en vaso"]]
].map(([id,name,category,price,art,description,steps])=>({id,name,category,price,art,description,steps}));
const hotIds = new Set(["espresso", "espresso-double", "espresso-panna", "americano", "latte", "cortado", "cappuccino", "cappuccino-vanilla", "frappe", "mocha", "dalgona", "breve", "hawaiian", "affogato", "caramel-latte", "vanilla-latte", "caramel-macchiato", "matcha", "submarino", "chocolate", "tea", "tea-black", "tea-green", "tea-chamomile"]);
for (const p of MENU) if(p.category==='bebida') p.temperature=hotIds.has(p.id)?'hot':'cold';
const FROSTINGS=[{id:'cream',name:'Crema',color:'#fff4da'},{id:'lavender',name:'Crema y lavanda',color:'#bcb0d4'},{id:'chocolate',name:'Crema con chocolate',color:'#795046'}];
function same(a,b){return a.id===b.id&&(!['roll','apple-roll'].includes(a.id)||a.frosting===b.frosting)}
function validateOrder(expected,actual,delivery,selected){if(delivery!==selected)return {ok:false,reason:delivery==='takeaway'?'Este pedido es para llevar: usá la caja.':'Este pedido es para comer aquí: usá el plato.'};const copy=[...actual];for(const e of expected){const i=copy.findIndex(a=>same(a,e));if(i<0)return {ok:false,reason:'Revisá los productos y el frosting del ticket. Podés retirar un producto de la bandeja y prepararlo otra vez.'};copy.splice(i,1)}return copy.length?{ok:false,reason:'Hay productos de más en la bandeja.'}:{ok:true};}
root.CafeData={MENU,FROSTINGS,validateOrder};if(typeof module!=='undefined')module.exports=root.CafeData;
})(typeof window!=='undefined'?window:globalThis);
