'use strict';
// Local audio stays outside #app so changing tables never restarts a song.
const cafeAudio=new Audio('assets/music/vintage-000.ogg');cafeAudio.loop=false;cafeAudio.volume=.3;cafeAudio.preload='none';
const ambientPartCount=18;let ambientPart=0;
const nextAmbient=new Audio();nextAmbient.preload='auto';
function ambientPath(part){return 'assets/music/vintage-'+String(part).padStart(3,'0')+'.ogg'}
function preloadAmbient(){if(!cafeAudioURL)nextAmbient.src=ambientPath((ambientPart+1)%ambientPartCount)}
cafeAudio.addEventListener('ended',()=>{if(cafeAudioURL)return;ambientPart=(ambientPart+1)%ambientPartCount;cafeAudio.src=ambientPath(ambientPart);playAmbient()});
let cafeAudioURL=null,cafeSongTitle='Vintage Bakery — Solace Crossing',cafeAudioDB=null;
function audioDatabase(){if(cafeAudioDB)return cafeAudioDB;cafeAudioDB=new Promise((resolve,reject)=>{const request=indexedDB.open('canela-music',1);request.onupgradeneeded=()=>request.result.createObjectStore('songs');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});return cafeAudioDB}
async function rememberAudio(file){try{const db=await audioDatabase();await new Promise((resolve,reject)=>{const tx=db.transaction('songs','readwrite');tx.objectStore('songs').put(file,'ambient');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}catch{toast('La canción funciona en esta sesión, pero no se pudo guardar para la próxima.')}}
function attachAudio(file){if(cafeAudioURL)URL.revokeObjectURL(cafeAudioURL);cafeAudioURL=URL.createObjectURL(file);cafeAudio.src=cafeAudioURL;cafeAudio.loop=true;nextAmbient.removeAttribute('src');nextAmbient.load();cafeSongTitle=(file.name||'Mi música del café').replace(/\.[^.]+$/,'');refreshMusicLabel()}
function refreshMusicLabel(){document.querySelectorAll('.ambient-title').forEach(el=>el.textContent=cafeSongTitle?(cafeAudio.paused?'Ⅱ ':'♫ ')+cafeSongTitle:'♪ Música de ambiente');document.querySelectorAll('[data-action="sound"]').forEach(el=>{el.setAttribute('aria-label',cafeSongTitle?(cafeAudio.paused?'Reproducir música':'Pausar música'):'Elegir música de ambiente');el.title=cafeSongTitle||'Elegir música de ambiente'});const b=document.querySelector('#audio-play');if(b)b.textContent=cafeAudio.paused?'Reproducir ▶':'Pausar Ⅱ'}
async function playAmbient(){try{await cafeAudio.play();preloadAmbient();state.sound=true;refreshMusicLabel()}catch{state.sound=false;toast('No pude reproducir ese archivo. Probá con un MP3, OGG o WAV.')}}
function musicSettings(){modal(`<span class="eyebrow">UN POQUITO DE MÚSICA</span><h2>Solo el sonido, sin video.</h2><p>Vintage Bakery acompaña tu ratito en el café. Podés ajustar el volumen o elegir otra canción de tu PC.</p><label class="audio-upload">Elegir archivo de audio<input id="ambient-file" type="file" accept="audio/*,.mp3,.ogg,.wav,.m4a"></label><p class="audio-current">${cafeSongTitle?esc(cafeSongTitle):'Todavía no hay una canción cargada.'}</p><div class="audio-controls">${button(cafeAudio.paused?'Reproducir ▶':'Pausar Ⅱ','audio-play','primary',`id="audio-play" ${cafeSongTitle?'':'disabled'}`)}<label>Volumen <input id="ambient-volume" type="range" min="0" max="100" value="${Math.round(cafeAudio.volume*100)}" aria-label="Volumen de la música"></label></div><p class="audio-note">La música incluida suena completa y se repite al terminar. Si elegís otro archivo, queda guardado solamente en este navegador.</p><a class="audio-source" href="https://www.youtube.com/watch?v=VwR3LBbL6Jk" target="_blank" rel="noopener">Abrir Vintage Bakery en YouTube ↗</a>`,'audio-modal')}
toggleSound=function(){clearInterval(musicTimer);musicTimer=null;if(!cafeSongTitle){musicSettings();return}if(cafeAudio.paused)playAmbient();else{cafeAudio.pause();state.sound=false;refreshMusicLabel()}};
const compactMusicHeader=header;
header=function(){return compactMusicHeader().replace('<div class="top-center">un pequeño lugar para estar bien</div>','<button class="ambient-title" data-action="music-settings" title="Elegir canción y ajustar el volumen">'+esc(cafeSongTitle?(cafeAudio.paused?'Ⅱ ':'♫ ')+cafeSongTitle:'♪ Música de ambiente')+'</button>').replace('Abrir o cerrar la música de YouTube',cafeSongTitle?'Reproducir o pausar música':'Elegir música de ambiente').replace('Vintage Bakery · Música','Música de ambiente')};
window.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled||!['music-settings','audio-play'].includes(b.dataset.action))return;e.preventDefault();e.stopImmediatePropagation();if(b.dataset.action==='music-settings')musicSettings();else toggleSound()},true);
document.addEventListener('change',async e=>{if(e.target.id!=='ambient-file')return;const file=e.target.files?.[0];if(!file)return;if(!file.type.startsWith('audio/')&&!/\.(mp3|ogg|wav|m4a)$/i.test(file.name)){toast('Elegí un archivo de audio.');return}attachAudio(file);await playAmbient();musicSettings();rememberAudio(file)});
document.addEventListener('input',e=>{if(e.target.id==='ambient-volume')cafeAudio.volume=Number(e.target.value)/100});
cafeAudio.addEventListener('pause',()=>{state.sound=false;refreshMusicLabel()});cafeAudio.addEventListener('play',()=>{state.sound=true;refreshMusicLabel()});
(async()=>{try{const db=await audioDatabase();const file=await new Promise((resolve,reject)=>{const r=db.transaction('songs').objectStore('songs').get('ambient');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});if(file&&!cafeAudioURL)attachAudio(file)}catch{}})();
// Browsers permit ambient audio after the first deliberate interaction.
let ambientStarted=false;
function startAmbientFromGesture(e){if(ambientStarted)return;ambientStarted=true;if(e.target.closest('[data-action="sound"],[data-action="audio-play"],[data-action="music-settings"]'))return;playAmbient()}
window.addEventListener('pointerdown',startAmbientFromGesture,true);
window.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')startAmbientFromGesture(e)},true);
render();
