'use strict';
const studio={color:'#9161a1',size:12,tool:'brush',draft:null,undo:[],redo:[],title:'Mi ratito en Canela',drawing:false,before:null,canvas:null,ctx:null};
let artGallery=[];try{artGallery=JSON.parse(localStorage.getItem('canela-art-v1')||'[]').filter(a=>typeof a.name==='string'&&/^data:image\/png;base64,/.test(a.image)).slice(0,6)}catch{}
let towerBest=0;try{towerBest=Math.max(0,Number(localStorage.getItem('canela-tower-best'))||0)}catch{}
let tower={rows:TableRules.newTower(),moves:0,sway:0,stability:100,selected:null,fallen:false,position:0},towerRAF=0;
const gameGuest=guest;
guest=function(){let html=gameGuest();if(state.seat!==null)html=html.replace('</h2>','</h2>'+button('Pintar o jugar ♡','table-games','table-play'));return html};
function stopTowerMeter(){cancelAnimationFrame(towerRAF);towerRAF=0}
const gameCloseModal=closeModal;
closeModal=function(cancel=true){if(cancel){finishStroke();stopTowerMeter();tower.selected=null}gameCloseModal(cancel)};
function gamesMenu(){stopTowerMeter();tower.selected=null;modal(`<span class="eyebrow">UN RATITO EN TU MESA</span><h2>Algo lindo mientras te quedás.</h2><p>Podés jugar mientras Delfi prepara tu pedido. Tu merienda te espera al cerrar esta ventana.</p><div class="table-game-cards"><button data-action="paint-open"><span class="game-card-art paint-card-art"><i></i><i></i><i></i></span><strong>Un lienzo para vos</strong><p>Pintá, guardá tu obra y llevátela en una imagen.</p><small>Abrir el taller →</small></button><button data-action="tower-open"><span class="game-card-art tower-card-art"><i></i><i></i><i></i><i></i></span><strong>Torre de sobremesa</strong><p>Sacá bloques con cuidado y volvé a apilarlos arriba.</p><small>Jugar con la torre →</small></button></div>${button('Mis recuerdos ('+artGallery.length+')','art-gallery','secondary')}`,'table-games-modal')}
function paintModal(){stopTowerMeter();modal(`<div class="paint-heading"><span class="eyebrow">TALLER DE SOBREMESA</span><h2>Dejá un poquito de vos.</h2><p>Arrastrá el pincel sobre el lienzo. Al terminar, podés llevarte tu pintura.</p></div><div class="paint-layout"><aside class="paint-tools"><span class="eyebrow">COLORES</span><div class="paint-palette">${['#9161a1','#db8e99','#cb6550','#dfae51','#839f6a','#5b8176','#6c91b2','#79563e','#302e34','#ffffff'].map(c=>`<button class="paint-color ${studio.color===c?'selected':''}" style="--paint:${c}" data-action="paint-color" data-color="${c}" aria-label="Color ${c}" aria-pressed="${studio.color===c}"></button>`).join('')}</div><label class="custom-color">Otro color <input id="paint-custom-color" type="color" value="${studio.color}"></label><label class="brush-size">Grosor <input id="brush-size" type="range" min="2" max="40" value="${studio.size}" aria-label="Grosor del pincel"></label><div class="paint-tool-buttons">${[['brush','Pincel'],['eraser','Goma'],['flower','Flor'],['heart','Corazón']].map(([t,n])=>button(n,'paint-tool','paint-tool '+(studio.tool===t?'selected':''),`data-tool="${t}" aria-pressed="${studio.tool===t}"`)).join('')}</div><div class="paint-history">${button('↶ Deshacer','paint-undo','text-button',studio.undo.length?'':'disabled')}${button('↷ Rehacer','paint-redo','text-button',studio.redo.length?'':'disabled')}</div>${button('Lienzo nuevo','paint-clear','text-button')}</aside><div class="easel"><canvas id="paint-canvas" width="800" height="520" aria-label="Lienzo para dibujar con el mouse o el dedo"></canvas><span>HECHO EN CANELA & COFFEE · CON CARIÑO</span></div></div><div class="paint-bottom"><label>Nombre de tu obra<input id="painting-name" maxlength="50" value="${esc(studio.title)}"></label><div>${button('Guardar recuerdo ♡','paint-save','secondary')}${button('Llevarme mi pintura ↓','paint-download','primary')}</div></div><p class="paint-note" id="paint-feedback" role="status">Tu borrador se conserva durante esta partida. Guardá un recuerdo para verlo en próximas visitas.</p>`,'paint-modal');
 studio.canvas=document.querySelector('#paint-canvas');studio.ctx=studio.canvas.getContext('2d');studio.ctx.fillStyle='#ffffff';studio.ctx.fillRect(0,0,800,520);const canvas=studio.canvas;if(studio.draft){const img=new Image();canvas.dataset.ready='false';img.onload=()=>{if(studio.canvas===canvas){studio.ctx.drawImage(img,0,0);canvas.dataset.ready='true'}};img.src=studio.draft}else canvas.dataset.ready='true';
 canvas.addEventListener('pointerdown',startStroke);canvas.addEventListener('pointermove',moveStroke);canvas.addEventListener('pointerup',finishStroke);canvas.addEventListener('pointercancel',finishStroke);canvas.addEventListener('lostpointercapture',finishStroke);
}
function paintPoint(e){const r=studio.canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*800/r.width,y:(e.clientY-r.top)*520/r.height}}
function startStroke(e){if(e.button!==0||studio.canvas.dataset.ready!=='true')return;e.preventDefault();studio.before=studio.canvas.toDataURL();studio.drawing=true;studio.canvas.setPointerCapture(e.pointerId);const p=paintPoint(e),ctx=studio.ctx;ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=studio.size;ctx.strokeStyle=studio.tool==='eraser'?'#ffffff':studio.color;ctx.fillStyle=ctx.strokeStyle;
 if(studio.tool==='flower'||studio.tool==='heart'){paintStamp(p);finishStroke();return}ctx.beginPath();ctx.arc(p.x,p.y,studio.size/2,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(p.x,p.y);
}
function moveStroke(e){if(!studio.drawing)return;e.preventDefault();const p=paintPoint(e);studio.ctx.lineTo(p.x,p.y);studio.ctx.stroke()}
function paintStamp(p){const c=studio.ctx,r=Math.max(12,studio.size*1.8);c.save();c.translate(p.x,p.y);c.fillStyle=studio.color;if(studio.tool==='flower'){for(let i=0;i<6;i++){c.rotate(Math.PI/3);c.beginPath();c.ellipse(0,-r*.55,r*.28,r*.5,0,0,Math.PI*2);c.fill()}c.fillStyle='#e6bc60';c.beginPath();c.arc(0,0,r*.25,0,Math.PI*2);c.fill()}else{c.beginPath();c.moveTo(0,r*.65);c.bezierCurveTo(-r*1.4,-r*.2,-r*.65,-r*1.4,0,-r*.55);c.bezierCurveTo(r*.65,-r*1.4,r*1.4,-r*.2,0,r*.65);c.fill()}c.restore()}
function finishStroke(){if(!studio.drawing)return;studio.drawing=false;studio.undo.push(studio.before);if(studio.undo.length>15)studio.undo.shift();studio.redo=[];studio.draft=studio.canvas.toDataURL();updatePaintTools()}
function updatePaintTools(){document.querySelectorAll('[data-action="paint-color"]').forEach(b=>{b.classList.toggle('selected',b.dataset.color===studio.color);b.setAttribute('aria-pressed',b.dataset.color===studio.color)});document.querySelectorAll('[data-action="paint-tool"]').forEach(b=>{b.classList.toggle('selected',b.dataset.tool===studio.tool);b.setAttribute('aria-pressed',b.dataset.tool===studio.tool)});for(const [a,stack] of [['paint-undo',studio.undo],['paint-redo',studio.redo]]){const b=document.querySelector(`[data-action="${a}"]`);if(b)b.disabled=!stack.length}}
function paintHistory(back){finishStroke();const from=back?studio.undo:studio.redo,to=back?studio.redo:studio.undo;if(!from.length)return;to.push(studio.canvas.toDataURL());studio.draft=from.pop();paintModal()}
function newCanvas(){finishStroke();studio.undo.push(studio.canvas.toDataURL());studio.redo=[];studio.ctx.fillStyle='#ffffff';studio.ctx.fillRect(0,0,800,520);studio.draft=studio.canvas.toDataURL();updatePaintTools();document.querySelector('#paint-feedback').textContent='Lienzo nuevo. Podés deshacer para recuperar el anterior.'}
function paintingRecord(){finishStroke();return {id:Date.now().toString(36),name:studio.title.trim()||'Mi ratito en Canela',image:studio.canvas.toDataURL(),seat:seats[state.seat]?.name||'Canela & Coffee',date:new Date().toLocaleDateString('es-UY')}}
function savePainting(){const a=paintingRecord();artGallery=[a,...artGallery].slice(0,6);try{localStorage.setItem('canela-art-v1',JSON.stringify(artGallery));document.querySelector('#paint-feedback').textContent='¡Guardado! Lo vas a encontrar en Mis recuerdos. Se conservan los últimos seis.'}catch{document.querySelector('#paint-feedback').textContent='No hay espacio para guardarlo en el navegador. Descargá tu pintura para conservarla.'}tone(784,.3)}
function downloadPainting(a){const link=document.createElement('a');link.href=a.image;link.download=(a.name.replace(/[^\p{L}\p{N} _-]/gu,'').trim()||'Mi-lienzo')+'.png';document.body.appendChild(link);link.click();link.remove()}
function galleryModal(){modal(`<span class="eyebrow">TE LLEVÁS ALGO LINDO</span><h2>Mis recuerdos del café.</h2><p>Los últimos seis lienzos guardados en este navegador. Podés descargarlos cuando quieras.</p><div class="art-gallery">${artGallery.length?artGallery.map(a=>`<article><img src="${a.image}" alt="${esc(a.name)}"><h3>${esc(a.name)}</h3><p>${esc(a.seat)} · ${esc(a.date)}</p>${button('Descargar PNG ↓','gallery-download','secondary',`data-id="${a.id}"`)}</article>`).join(''):'<p class="empty-gallery">Tu primera obra todavía te está esperando.</p>'}</div>${button('Volver al lienzo','paint-open','primary')}`,'gallery-modal')}
function towerModal(){stopTowerMeter();tower.selected=null;modal(`<span class="eyebrow">TORRE DE SOBREMESA</span><h2>Un bloque, mucha calma.</h2><p>Elegí un bloque de abajo y frená la aguja en verde para sacarlo con suavidad. Se apila arriba. ¡No dejes un piso sin apoyo!</p><div class="tower-layout"><div class="tower-scene ${tower.fallen?'tower-fallen':''}"><div class="block-tower">${tower.rows.map((row,i)=>`<div class="tower-row ${i%2?'cross-row':''}" data-row="${i}">${row.map((on,j)=>`<button class="wood-block ${on?'':'missing'}" data-action="tower-select" data-row="${i}" data-col="${j}" ${!on||i===tower.rows.length-1||tower.fallen?'disabled':''} aria-label="Piso ${i+1}, bloque ${j+1}${i===tower.rows.length-1?', protegido':''}"><span>${on?'✧':''}</span></button>`).join('')}</div>`).reverse().join('')}</div><div class="tower-table"></div></div><aside class="tower-sidebar"><div class="tower-score"><strong>${tower.moves}</strong><span>bloques extraídos</span></div><div class="tower-best">Tu récord: ${towerBest}</div><label>Estabilidad <progress id="tower-stability" max="100" value="${tower.stability}"></progress></label><div id="tower-instructions" role="status">${tower.fallen?'<h3>¡Se cayó!</h3><p>No pasa nada, armamos otra. ♡</p>':'Elegí un bloque de la torre. El piso de arriba está protegido.'}</div><div id="tower-pull-area"></div>${button('Armar otra torre','tower-reset','secondary')}${button('Volver a los juegos','table-games','text-button')}</aside></div>`,'tower-modal')}
function selectBlock(row,col){if(tower.fallen||row>=tower.rows.length-1||!tower.rows[row]?.[col])return;stopTowerMeter();tower.selected={row,col};document.querySelectorAll('.wood-block').forEach(b=>b.classList.toggle('picked',Number(b.dataset.row)===row&&Number(b.dataset.col)===col));const trial=TableRules.pull(tower.rows,row,col,1,tower.sway);document.querySelector('#tower-instructions').textContent=trial.fallen?'Ese bloque sostiene demasiado: sacarlo puede tirar la torre. Podés elegir otro.':'Sacalo despacito. Frená la aguja dentro del verde.';document.querySelector('#tower-pull-area').innerHTML='<div class="tower-gauge"><span></span><i id="tower-needle"></i></div>'+button('Sacar bloque · ESPACIO','tower-pull','primary');const start=performance.now();function tick(t){const needle=document.querySelector('#tower-needle');if(!needle){towerRAF=0;return}tower.position=(1-Math.cos((t-start)/650))/2;needle.style.left=(tower.position*100)+'%';towerRAF=requestAnimationFrame(tick)}towerRAF=requestAnimationFrame(tick)}
function pullBlock(){if(!tower.selected||tower.fallen)return;stopTowerMeter();const precision=Math.max(0,1-Math.max(0,Math.abs(tower.position-.5)-.15)/.35);const r=TableRules.pull(tower.rows,tower.selected.row,tower.selected.col,precision,tower.sway);if(!r.ok)return;tower={...tower,...r,selected:null,moves:tower.moves+(r.fallen?0:1)};if(tower.moves>towerBest){towerBest=tower.moves;try{localStorage.setItem('canela-tower-best',towerBest)}catch{}}tone(r.fallen?180:700,.3);towerModal();if(!r.fallen)document.querySelector('#tower-instructions').textContent=precision>.85?'¡Suavecito! Un bloque más arriba.':'Se movió un poquito… elegí el próximo con cuidado.'}
const gameActions=['table-games','paint-open','paint-color','paint-tool','paint-undo','paint-redo','paint-clear','paint-save','paint-download','art-gallery','gallery-download','tower-open','tower-select','tower-pull','tower-reset'];
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled||!gameActions.includes(b.dataset.action))return;e.preventDefault();e.stopImmediatePropagation();switch(b.dataset.action){case'table-games':gamesMenu();break;case'paint-open':paintModal();break;case'paint-color':studio.color=b.dataset.color;studio.tool='brush';updatePaintTools();break;case'paint-tool':studio.tool=b.dataset.tool;updatePaintTools();break;case'paint-undo':paintHistory(true);break;case'paint-redo':paintHistory(false);break;case'paint-clear':newCanvas();break;case'paint-save':savePainting();break;case'paint-download':downloadPainting(paintingRecord());break;case'art-gallery':galleryModal();break;case'gallery-download':{const a=artGallery.find(a=>a.id===b.dataset.id);if(a)downloadPainting(a);break}case'tower-open':towerModal();break;case'tower-select':selectBlock(Number(b.dataset.row),Number(b.dataset.col));break;case'tower-pull':pullBlock();break;case'tower-reset':tower={rows:TableRules.newTower(),moves:0,sway:0,stability:100,selected:null,fallen:false,position:0};towerModal();break}},true);
document.addEventListener('input',e=>{if(e.target.id==='paint-custom-color'){studio.color=e.target.value;studio.tool='brush';updatePaintTools()}if(e.target.id==='brush-size')studio.size=Number(e.target.value);if(e.target.id==='painting-name')studio.title=e.target.value});
document.addEventListener('keydown',e=>{if(e.code==='Space'&&tower.selected&&document.querySelector('#tower-needle')&&!e.target.matches('input,textarea')){e.preventDefault();pullBlock()}});
render();
