const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path'),playRecipe=require('./skill-play.cjs');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox']});try{const p=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(15000);await p.goto('file://'+path.resolve(__dirname,'../index.html'));
 await p.click('[data-action=work]');await p.click('.modal [data-action=close]');await p.waitForFunction(()=>state.customerPhase==='waiting');
 await p.click('[data-action=catalog][data-category=dulce]');await p.click('[data-action=prepare][data-id=roll]');
 // A wrong ingredient is a real drag and visibly reduces the recipe's quality.
 const index=await p.evaluate(()=>mini.cards.findIndex(c=>c.label==='sal extra'));let box=await p.locator('#skill-canvas').boundingBox();await p.mouse.move(box.x+(100+index*152)*box.width/800,box.y+66*box.height/390);await p.mouse.down();await p.mouse.move(box.x+400*box.width/800,box.y+256*box.height/390,{steps:12});await p.mouse.up();assert.equal(await p.evaluate(()=>mini.score),82);
 await playRecipe(p);assert.ok(await p.evaluate(()=>state.tray[0].quality<100));await p.click('[data-action=catalog][data-category=hot]');await p.click('[data-action=prepare][data-id=latte]');await playRecipe(p);
 await p.click('[data-action=pack][data-id=takeaway]');await p.click('[data-action=serve]');assert.equal(await p.evaluate(()=>state.customerClock.mistakes),1);assert.equal(await p.evaluate(()=>progress.served),0);
 await p.click('[data-action=pack][data-id=here]');await p.click('[data-action=serve]');assert.equal(await p.evaluate(()=>progress.served),1);assert.ok(await p.evaluate(()=>state.lastRating<5));await p.waitForFunction(()=>!state.serving);
 // Low quality is accepted but yields a disappointed face and no tip.
 await p.evaluate(()=>{state.tray=state.orders[0].items.map(x=>({...x,quality:20}));state.delivery=state.orders[0].delivery;state.customerClock.left=10;render()});await p.click('[data-action=serve]');assert.equal(await p.evaluate(()=>state.lastRating),1);assert.equal(await p.locator('.mood-stage').getAttribute('data-mood'),'upset');assert.equal(await p.evaluate(()=>state.shiftReviews.at(-1).tip),0);await p.screenshot({path:'/tmp/customer-disappointed.png'});await p.waitForFunction(()=>!state.serving);
 // Reading the shop pauses the active order, then the clock resumes.
 await p.waitForFunction(()=>state.customerPhase==='waiting');
 await p.click('.shop-trigger');const before=await p.evaluate(()=>state.customerClock.left);await p.waitForTimeout(600);assert.equal(await p.evaluate(()=>state.customerClock.left),before);await p.click('.close-button');await p.waitForTimeout(600);assert.ok(await p.evaluate(()=>state.customerClock.left)<before);
 // Deadline cancels an active preparation, advances the queue once, pays nothing.
 await p.evaluate(()=>{prepStart('latte');state.customerClock.left=.05});await p.waitForFunction(()=>state.serving);assert.equal(await p.locator('#skill-canvas').count(),0);assert.equal(await p.evaluate(()=>state.lastEarning),0);const count=await p.evaluate(()=>state.completed);await p.waitForFunction(()=>!state.serving);assert.equal(await p.evaluate(()=>state.completed),count);
 // Exercise the salado cutting and heat gestures, too.
 await p.evaluate(()=>prepStart('cheese-scone'));await playRecipe(p);assert.ok(await p.evaluate(()=>state.tray[0].quality>=85));
 // Complete the turn and show both happy and unhappy reviews.
 for(let i=0;i<2;i++){await p.evaluate(()=>{state.tray=state.orders[0].items.map(x=>({...x,quality:100}));state.delivery=state.orders[0].delivery;state.customerClock.left=state.customerClock.total;render()});await p.click('[data-action=serve]');assert.equal(await p.evaluate(()=>state.lastRating),5);if(i===0)await p.waitForFunction(()=>!state.serving)}await p.waitForFunction(()=>state.scene==='summary');assert.equal(await p.locator('.review-grid article').count(),5);
 // Purchase/equip state persists, locked purchases cannot deduct money.
 await p.evaluate(()=>{progress.coins=1000;progress.served=5;save();render()});await p.click('[data-action=shop]');await p.click('[data-action=shop-preview][data-id=flowers]');await p.click('[data-action=buy-upgrade][data-id=flowers]');assert.equal(await p.evaluate(()=>progress.coins),900);await p.click('[data-action=equip-upgrade][data-id=flowers]');assert.equal(await p.evaluate(()=>hasUpgrade('flowers')),false);await p.reload();assert.equal(await p.evaluate(()=>hasUpgrade('flowers')),false);assert.equal(await p.evaluate(()=>progress.coins),900);assert.equal(await p.evaluate(()=>progress.reviews.length),5);
 await p.click('.shop-trigger');await p.click('[data-action=shop-preview][data-id=flowers]');await p.click('[data-action=equip-upgrade][data-id=flowers]');assert.equal(await p.evaluate(()=>hasUpgrade('flowers')),true);assert.equal(await p.evaluate(()=>progress.coins),900);
 assert.deepEqual(errors,[]);console.log('PASS: mouse minigames, quality, wrong orders, expressions, patience/pause/expiry, five reviews, shop purchase/equip persistence.');
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
